! mkdir data

In [1]:
import numpy as np
import pandas as pd

# Booking

In [2]:
booking = pd.read_csv('./booking/bookingSolPlaya.csv', decimal=',')
booking

,airports,beaches,city,comments,name,popular_services,prices,quality_price,rating,services,stars,url
0,NaN,NaN,"\nMéxico\n,\nNayarit\n,\nCompostela\n",64 comentarios,\nJARDIN DE ESTRELLAS\n,NaN,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4,https://www.booking.com/hotel/mx/jardin-de-est...
1,NaN,NaN,"\nMéxico\n,\nCampeche\n,\nIsla Aguada\n",235 comentarios,"\nFreedom Shores ""La Gringa"" Hotel - Universal...",NaN,"\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3,https://www.booking.com/hotel/mx/freedom-shore...
2,NaN,NaN,"\nTodas las opciones de apartahoteles\n,\nMéxi...",14 comentarios,\nHOTEL CANTO\n,NaN,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3,https://www.booking.com/hotel/mx/canto-bacalar...
3,NaN,NaN,"\nMéxico\n,\nQuintana Roo\n,\nBacalar\n",NaN,\n,NaN,"\nMXN 900\n,\nMXN 800\n,\nMXN 1,100\n,\nMXN 1,...",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0,https://www.booking.com/hotel/mx/catedral-baca...
4,NaN,NaN,"\nMéxico\n,\nQuintana Roo\n,\nBacalar\n",21 comentarios,\nCabañas Colibrí\n,NaN,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,https://www.booking.com/hotel/mx/cabanas-colib...
...,...,...,...,...,...,...,...,...,...,...,...,...
937,NaN,NaN,\nTodas las opciones de habitaciones en casas ...,NaN,\n,NaN,"\nMXN 1,058\n",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0,https://www.booking.com/hotel/mx/habitacion-ta...
938,NaN,NaN,"\nTodas las opciones de villas\n,\nMéxico\n,\n...",NaN,\nCASA BODHI TULUM -city villa with pool-\n,NaN,"\nMXN 5,977\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,https://www.booking.com/hotel/mx/casa-wabi-tul...
939,NaN,NaN,"\nTodas las opciones de apartamentos\n,\nMéxic...",4 comentarios,\nTaanah Poolview 1BR apartment Ecochic\n,NaN,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,https://www.booking.com/hotel/mx/taanah-poolvi...
940,NaN,NaN,"\nTodas las opciones de apartamentos\n,\nMéxic...",NaN,\nBlue Luxury 1 BD Apartment - Direct exit to ...,NaN,"\nMXN 1,360\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,https://www.booking.com/hotel/mx/blue-luxury-b...
941,NaN,NaN,"\nTodas las opciones de villas\n,\nMéxico\n,\n...",3 comentarios,\nBIT TULUM Villas\n,NaN,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4,https://www.booking.com/hotel/mx/bit-tulum.es....

In [3]:
booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airports          0 non-null      float64
 1   beaches           0 non-null      float64
 2   city              942 non-null    object
 3   comments          690 non-null    object
 4   name              942 non-null    object
 5   popular_services  0 non-null      float64
 6   prices            942 non-null    object
 7   quality_price     690 non-null    object
 8   rating            690 non-null    float64
 9   services          942 non-null    object
 10  stars             942 non-null    int64
 11  url               942 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 88.4+ KB

In [4]:
booking.drop(['airports', 'beaches','popular_services','url'],axis=1,inplace=True)

## City

In [5]:
booking.city = booking.city.apply(lambda x: str(x).replace(",","\n").strip().split("\n")[-1])
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64 comentarios,\nJARDIN DE ESTRELLAS\n,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235 comentarios,"\nFreedom Shores ""La Gringa"" Hotel - Universal...","\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14 comentarios,\nHOTEL CANTO\n,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
3,Bacalar,NaN,\n,"\nMXN 900\n,\nMXN 800\n,\nMXN 1,100\n,\nMXN 1,...",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
4,Bacalar,21 comentarios,\nCabañas Colibrí\n,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
...,...,...,...,...,...,...,...,...
937,Tulum,NaN,\n,"\nMXN 1,058\n",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
938,Tulum,NaN,\nCASA BODHI TULUM -city villa with pool-\n,"\nMXN 5,977\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4
939,Tulum,4 comentarios,\nTaanah Poolview 1BR apartment Ecochic\n,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
940,Tulum,NaN,\nBlue Luxury 1 BD Apartment - Direct exit to ...,"\nMXN 1,360\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4
941,Tulum,3 comentarios,\nBIT TULUM Villas\n,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

In [6]:
booking.city = booking.city.str.replace('Centro Tulum','Tulum')
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64 comentarios,\nJARDIN DE ESTRELLAS\n,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235 comentarios,"\nFreedom Shores ""La Gringa"" Hotel - Universal...","\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14 comentarios,\nHOTEL CANTO\n,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
3,Bacalar,NaN,\n,"\nMXN 900\n,\nMXN 800\n,\nMXN 1,100\n,\nMXN 1,...",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
4,Bacalar,21 comentarios,\nCabañas Colibrí\n,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
...,...,...,...,...,...,...,...,...
937,Tulum,NaN,\n,"\nMXN 1,058\n",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
938,Tulum,NaN,\nCASA BODHI TULUM -city villa with pool-\n,"\nMXN 5,977\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4
939,Tulum,4 comentarios,\nTaanah Poolview 1BR apartment Ecochic\n,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
940,Tulum,NaN,\nBlue Luxury 1 BD Apartment - Direct exit to ...,"\nMXN 1,360\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4
941,Tulum,3 comentarios,\nBIT TULUM Villas\n,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

In [7]:
booking.sort_values('city',inplace=True)

In [8]:
booking['id'] = np.arange(booking.shape[0]) + 1

In [9]:
booking['rank'] = np.int64(booking.groupby('city')['id'].rank('first'))

In [10]:
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166 comentarios,\nHabitas Bacalar\n,"\nMXN 5,977\n,\nMXN 7,770\n,\nMXN 8,766\n,\nMX...",8.8,9.5,"\n,\n,\n,\n,\n,\nSpa y centro de bienestar\n,\...",5,1,1
114,Bacalar,10 comentarios,\nXO Hotel Bacalar Lakefront - All Inclusive\n,"\nMXN 2,745\n,\nMXN 3,402\n,\nMXN 3,512\n,\nMX...",7.2,7.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,2,2
115,Bacalar,419 comentarios,\nXibalba in town\n,"\nMXN 1,200\n,\nMXN 450\n",8.5,8.2,"\n,\n,\n,\n,\n,\nToallas de playa/piscina\n,\n...",0,3,3
116,Bacalar,367 comentarios,\nBlue Bird\n,"\nMXN 2,964\n,\nMXN 2,994\n,\nMXN 3,005\n,\nMX...",7.9,8.7,"\n,\n,\n,\n,\n,\nSombrillas\n,\n,\n,\n,\n,\n,\...",0,4,4
117,Bacalar,295 comentarios,\nHotel Casa Ariana\n,"\nMXN 720\n,\nMXN 770\n,\nMXN 810\n,\nMXN 860\...",8.6,8.4,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",2,5,5
...,...,...,...,...,...,...,...,...,...,...
516,Zama,224 comentarios,\nThe Highline Tulum\n,"\nMXN 1,646\n,\nMXN 2,259\n,\nMXN 2,678\n,\nMX...",8.2,8.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,938,8
629,Zama,190 comentarios,\nZereno Boutique Hotel\n,"\nMXN 1,505\n,\nMXN 2,072\n,\nMXN 2,072\n,\nMX...",8.9,8.9,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,939,9
479,Zama,123 comentarios,\nHotel Mamazul Tulum\n,"\nMXN 3,012\n,\nMXN 4,184\n,\nMXN 4,614\n,\nMX...",8.6,8.5,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,940,10
509,Zama,276 comentarios,\nKoos Hotel Tulum\n,"\nMXN 842\n,\nMXN 943\n,\nMXN 936\n,\nMXN 1,04...",8.2,7.8,"\n,\n,\n,\n,\n,\nZona de pícnic\n,\n,\n,\n,\n,...",4,941,11
599,Zama,363 comentarios,\nKuukum Tulum Hotel\n,"\nMXN 2,753\n,\nMXN 3,059\n,\nMXN 3,638\n,\nMX...",8.2,8.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,942,12

In [11]:
booking.dropna(inplace=True)

## Comments

In [12]:
booking.comments = booking.comments.apply(lambda x: x.split()[0] if str(x)!="nan" else 0)
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166,\nHabitas Bacalar\n,"\nMXN 5,977\n,\nMXN 7,770\n,\nMXN 8,766\n,\nMX...",8.8,9.5,"\n,\n,\n,\n,\n,\nSpa y centro de bienestar\n,\...",5,1,1
114,Bacalar,10,\nXO Hotel Bacalar Lakefront - All Inclusive\n,"\nMXN 2,745\n,\nMXN 3,402\n,\nMXN 3,512\n,\nMX...",7.2,7.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,2,2
115,Bacalar,419,\nXibalba in town\n,"\nMXN 1,200\n,\nMXN 450\n",8.5,8.2,"\n,\n,\n,\n,\n,\nToallas de playa/piscina\n,\n...",0,3,3
116,Bacalar,367,\nBlue Bird\n,"\nMXN 2,964\n,\nMXN 2,994\n,\nMXN 3,005\n,\nMX...",7.9,8.7,"\n,\n,\n,\n,\n,\nSombrillas\n,\n,\n,\n,\n,\n,\...",0,4,4
117,Bacalar,295,\nHotel Casa Ariana\n,"\nMXN 720\n,\nMXN 770\n,\nMXN 810\n,\nMXN 860\...",8.6,8.4,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",2,5,5
...,...,...,...,...,...,...,...,...,...,...
516,Zama,224,\nThe Highline Tulum\n,"\nMXN 1,646\n,\nMXN 2,259\n,\nMXN 2,678\n,\nMX...",8.2,8.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,938,8
629,Zama,190,\nZereno Boutique Hotel\n,"\nMXN 1,505\n,\nMXN 2,072\n,\nMXN 2,072\n,\nMX...",8.9,8.9,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,939,9
479,Zama,123,\nHotel Mamazul Tulum\n,"\nMXN 3,012\n,\nMXN 4,184\n,\nMXN 4,614\n,\nMX...",8.6,8.5,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,940,10
509,Zama,276,\nKoos Hotel Tulum\n,"\nMXN 842\n,\nMXN 943\n,\nMXN 936\n,\nMXN 1,04...",8.2,7.8,"\n,\n,\n,\n,\n,\nZona de pícnic\n,\n,\n,\n,\n,...",4,941,11
599,Zama,363,\nKuukum Tulum Hotel\n,"\nMXN 2,753\n,\nMXN 3,059\n,\nMXN 3,638\n,\nMX...",8.2,8.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,942,12

## Name

In [13]:
booking.name = booking.name.apply(lambda x: x.strip())
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166,Habitas Bacalar,"\nMXN 5,977\n,\nMXN 7,770\n,\nMXN 8,766\n,\nMX...",8.8,9.5,"\n,\n,\n,\n,\n,\nSpa y centro de bienestar\n,\...",5,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,"\nMXN 2,745\n,\nMXN 3,402\n,\nMXN 3,512\n,\nMX...",7.2,7.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,2,2
115,Bacalar,419,Xibalba in town,"\nMXN 1,200\n,\nMXN 450\n",8.5,8.2,"\n,\n,\n,\n,\n,\nToallas de playa/piscina\n,\n...",0,3,3
116,Bacalar,367,Blue Bird,"\nMXN 2,964\n,\nMXN 2,994\n,\nMXN 3,005\n,\nMX...",7.9,8.7,"\n,\n,\n,\n,\n,\nSombrillas\n,\n,\n,\n,\n,\n,\...",0,4,4
117,Bacalar,295,Hotel Casa Ariana,"\nMXN 720\n,\nMXN 770\n,\nMXN 810\n,\nMXN 860\...",8.6,8.4,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",2,5,5
...,...,...,...,...,...,...,...,...,...,...
516,Zama,224,The Highline Tulum,"\nMXN 1,646\n,\nMXN 2,259\n,\nMXN 2,678\n,\nMX...",8.2,8.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,938,8
629,Zama,190,Zereno Boutique Hotel,"\nMXN 1,505\n,\nMXN 2,072\n,\nMXN 2,072\n,\nMX...",8.9,8.9,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,939,9
479,Zama,123,Hotel Mamazul Tulum,"\nMXN 3,012\n,\nMXN 4,184\n,\nMXN 4,614\n,\nMX...",8.6,8.5,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,940,10
509,Zama,276,Koos Hotel Tulum,"\nMXN 842\n,\nMXN 943\n,\nMXN 936\n,\nMXN 1,04...",8.2,7.8,"\n,\n,\n,\n,\n,\nZona de pícnic\n,\n,\n,\n,\n,...",4,941,11
599,Zama,363,Kuukum Tulum Hotel,"\nMXN 2,753\n,\nMXN 3,059\n,\nMXN 3,638\n,\nMX...",8.2,8.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,942,12

## Prices

In [14]:
booking.prices = booking.prices.apply(lambda x: x.replace("MXN","").replace(",","").replace("\n\n","\n").strip().replace("\n"," #"))
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166,Habitas Bacalar,5977 # 7770 # 8766 # 8268 # 7172 # 9363 # 1035...,8.8,9.5,"\n,\n,\n,\n,\n,\nSpa y centro de bienestar\n,\...",5,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745 # 3402 # 3512 # 4169 # 4388 # 5046 # 3041...,7.2,7.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,2,2
115,Bacalar,419,Xibalba in town,1200 # 450,8.5,8.2,"\n,\n,\n,\n,\n,\nToallas de playa/piscina\n,\n...",0,3,3
116,Bacalar,367,Blue Bird,2964 # 2994 # 3005 # 3036 # 3011 # 3042 # 3434...,7.9,8.7,"\n,\n,\n,\n,\n,\nSombrillas\n,\n,\n,\n,\n,\n,\...",0,4,4
117,Bacalar,295,Hotel Casa Ariana,720 # 770 # 810 # 860 # 900 # 905 # 945 # 900,8.6,8.4,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",2,5,5
...,...,...,...,...,...,...,...,...,...,...
516,Zama,224,The Highline Tulum,1646 # 2259 # 2678 # 3076 # 3474,8.2,8.1,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,938,8
629,Zama,190,Zereno Boutique Hotel,1505 # 2072 # 2072 # 2456 # 2952 # 2952 # 3449,8.9,8.9,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,939,9
479,Zama,123,Hotel Mamazul Tulum,3012 # 4184 # 4614 # 4973 # 5785 # 8080,8.6,8.5,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,940,10
509,Zama,276,Koos Hotel Tulum,842 # 943 # 936 # 1048 # 2265 # 2537 # 2499 # ...,8.2,7.8,"\n,\n,\n,\n,\n,\nZona de pícnic\n,\n,\n,\n,\n,...",4,941,11
599,Zama,363,Kuukum Tulum Hotel,2753 # 3059 # 3638 # 4042 # 4369 # 3932 # 3343...,8.2,8.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,942,12

## Services

In [15]:
booking.services = booking.services.apply(lambda x: " # ".join(x.replace(",","").strip().replace("\n",";").split(";;;;;;;;;")).replace(";",""))
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166,Habitas Bacalar,5977 # 7770 # 8766 # 8268 # 7172 # 9363 # 1035...,8.8,9.5,Spa y centro de bienestarDe pago # Papel higié...,5,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745 # 3402 # 3512 # 4169 # 4388 # 5046 # 3041...,7.2,7.1,Abierta todo el año # Horario de apertura # Pa...,3,2,2
115,Bacalar,419,Xibalba in town,1200 # 450,8.5,8.2,Toallas de playa/piscina # Baño al aire libre ...,0,3,3
116,Bacalar,367,Blue Bird,2964 # 2994 # 3005 # 3036 # 3011 # 3042 # 3434...,7.9,8.7,Sombrillas # Tumbonas/sillas de playa # Toalla...,0,4,4
117,Bacalar,295,Hotel Casa Ariana,720 # 770 # 810 # 860 # 900 # 905 # 945 # 900,8.6,8.4,Papel higiénico # Toallas # Bañera o ducha # B...,2,5,5
...,...,...,...,...,...,...,...,...,...,...
516,Zama,224,The Highline Tulum,1646 # 2259 # 2678 # 3076 # 3474,8.2,8.1,Abierta todo el año # Toallas de playa/piscina...,4,938,8
629,Zama,190,Zereno Boutique Hotel,1505 # 2072 # 2072 # 2456 # 2952 # 2952 # 3449,8.9,8.9,Abierta todo el año # Horario de apertura # Pa...,0,939,9
479,Zama,123,Hotel Mamazul Tulum,3012 # 4184 # 4614 # 4973 # 5785 # 8080,8.6,8.5,Abierta todo el año # Solo para adultos # Tumb...,4,940,10
509,Zama,276,Koos Hotel Tulum,842 # 943 # 936 # 1048 # 2265 # 2537 # 2499 # ...,8.2,7.8,Zona de pícnic # Mobiliario exterior # Terraza...,4,941,11
599,Zama,363,Kuukum Tulum Hotel,2753 # 3059 # 3638 # 4042 # 4369 # 3932 # 3343...,8.2,8.0,Abierta todo el año # Horario de apertura # Pa...,4,942,12

In [16]:
PM = [
    'Compostela', 'Isla Aguada', 'Bacalar', 'Isla Mujeres', 
    'Sayulita', 'Todos Santos', 'Mazunte', 'Loreto', 
    'Tulum', 'Centro Tulum', 'Sisal', 'Papantla de Olarte'
]

In [17]:
booking = booking[booking.city.isin(PM)]
booking

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
164,Bacalar,166,Habitas Bacalar,5977 # 7770 # 8766 # 8268 # 7172 # 9363 # 1035...,8.8,9.5,Spa y centro de bienestarDe pago # Papel higié...,5,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745 # 3402 # 3512 # 4169 # 4388 # 5046 # 3041...,7.2,7.1,Abierta todo el año # Horario de apertura # Pa...,3,2,2
115,Bacalar,419,Xibalba in town,1200 # 450,8.5,8.2,Toallas de playa/piscina # Baño al aire libre ...,0,3,3
116,Bacalar,367,Blue Bird,2964 # 2994 # 3005 # 3036 # 3011 # 3042 # 3434...,7.9,8.7,Sombrillas # Tumbonas/sillas de playa # Toalla...,0,4,4
117,Bacalar,295,Hotel Casa Ariana,720 # 770 # 810 # 860 # 900 # 905 # 945 # 900,8.6,8.4,Papel higiénico # Toallas # Bañera o ducha # B...,2,5,5
...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,Mesa de comedor # Utensilios de cocina # Cocin...,4,926,528
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,Cocina # Lavadora # Ropa de cama # Armario # P...,3,927,529
530,Tulum,83,Tulum Nah,802 # 1061 # 1254 # 1447 # 1061 # 1254 # 1447 ...,8.6,8.3,Abierta todo el año # Toallas de playa/piscina...,3,928,530
531,Tulum,193,Casa Ganesh Tulum,4080 # 25500,8.0,8.3,Clases de yoga # Masaje corporal completoDe pa...,0,929,531
532,Tulum,10,Casa Bohemia,797 # 717 # 797 # 717 # 1721 # 1817 # 1913 # 1626,8.4,7.6,Papel higiénico # Toallas # Bañera o ducha # B...,0,930,532

In [18]:
booking.city.unique()

array(['Bacalar', 'Compostela', 'Isla Aguada', 'Isla Mujeres', 'Loreto',
       'Mazunte', 'Papantla de Olarte', 'Sayulita', 'Sisal',
       'Todos Santos', 'Tulum'], dtype=object)

In [19]:
booking.drop_duplicates(inplace=True)

<ipython-input-19-2b22e1efe0db>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  booking.drop_duplicates(inplace=True)

In [20]:
booking.to_csv('./data/booking_clean.csv',index=False)

In [21]:
bookingOHE = booking.drop("services",axis=1).join(booking.services.str.get_dummies(sep=" # "))
bookingOHE

,city,comments,name,prices,quality_price,rating,stars,id,rank,Abierta todo el año,...,Zona de estar,Zona de fumadores,Zona de juegos interior,Zona de juegos para niños,Zona de pícnic,Zona de spa / relajación,Zona poco profunda,Zona privada de playa,Zona privada de playaDe pago,iPad
164,Bacalar,166,Habitas Bacalar,5977 # 7770 # 8766 # 8268 # 7172 # 9363 # 1035...,8.8,9.5,5,1,1,0,...,0,0,0,0,0,0,0,0,0,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745 # 3402 # 3512 # 4169 # 4388 # 5046 # 3041...,7.2,7.1,3,2,2,1,...,0,1,0,0,0,1,1,1,0,0
115,Bacalar,419,Xibalba in town,1200 # 450,8.5,8.2,0,3,3,0,...,0,1,0,0,0,0,0,0,0,0
116,Bacalar,367,Blue Bird,2964 # 2994 # 3005 # 3036 # 3011 # 3042 # 3434...,7.9,8.7,0,4,4,0,...,0,0,0,0,0,0,0,1,0,0
117,Bacalar,295,Hotel Casa Ariana,720 # 770 # 810 # 860 # 900 # 905 # 945 # 900,8.6,8.4,2,5,5,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,4,926,528,0,...,0,0,0,0,0,0,0,0,0,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,...,0,0,0,0,0,0,0,0,0,0
530,Tulum,83,Tulum Nah,802 # 1061 # 1254 # 1447 # 1061 # 1254 # 1447 ...,8.6,8.3,3,928,530,1,...,0,1,0,0,0,0,0,0,0,0
531,Tulum,193,Casa Ganesh Tulum,4080 # 25500,8.0,8.3,0,929,531,0,...,0,0,0,0,0,0,0,1,0,0
532,Tulum,10,Casa Bohemia,797 # 717 # 797 # 717 # 1721 # 1817 # 1913 # 1626,8.4,7.6,0,930,532,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
bookingOHE.prices = booking.prices.apply(lambda x: int(x.split("#")[0]))
bookingOHE

,city,comments,name,prices,quality_price,rating,stars,id,rank,Abierta todo el año,...,Zona de estar,Zona de fumadores,Zona de juegos interior,Zona de juegos para niños,Zona de pícnic,Zona de spa / relajación,Zona poco profunda,Zona privada de playa,Zona privada de playaDe pago,iPad
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,0,...,0,0,0,0,0,0,0,0,0,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,...,0,1,0,0,0,1,1,1,0,0
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,...,0,1,0,0,0,0,0,0,0,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,0,...,0,0,0,0,0,0,0,1,0,0
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,...,0,0,0,0,0,0,0,0,0,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,...,0,0,0,0,0,0,0,0,0,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,1,...,0,1,0,0,0,0,0,0,0,0
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,0,...,0,0,0,0,0,0,0,1,0,0
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
bookingOHE.to_csv('./data/bookingSolPlaya_OHE.csv',index=False)

## Reducción de servicios en categorías:
+ **Heredados** Aquellos que provienen de recursos naturales
+ **Acceso y comunicación** Aquellos que permiten una comunicación al huésped, como el habla de idiomas extranjeros, wifi, teléfono, transporte, etc.
+ **Entretenimiento** Actividades extras dentro y fuera del hotel.
+ **Inclusión** Aquellos servicios que tienen en cuenta a personas algún tipo de discapacidad.
+ **Apto para infantes** Servicios que indican la inclusión de niños.
+ **Restaurante/Bar** Servicios en relación a la comida y bebidas.

In [24]:
booking_servicios = bookingOHE[bookingOHE.columns[:9]].copy()
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5
...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532

In [25]:
list(bookingOHE.columns[7:])

['id',
 'rank',
 'Abierta todo el año',
 'Acceso a pisos superiores en ascensor',
 'Acceso a pisos superiores solo mediante escaleras',
 'Acceso al salón executive',
 'Adaptado para sillas de ruedas',
 'Adaptado personas de movilidad reducida',
 'Adecuada para niños',
 'Adosado',
 'Aeróbic',
 'AeróbicDe pago',
 'AeróbicFuera del alojamientoDe pago',
 'Aire acondicionado',
 'Aire acondicionadoDe pago',
 'Alarma de seguridad',
 'Albornoz',
 'Alemán',
 'Almuerzos para llevar',
 'Alquiler de bicicletas (de pago)',
 'Alquiler de coches',
 'Apartamento privado en edificio',
 'Apoyo visual: braille',
 'Apoyo visual: carteles táctiles',
 'Armario',
 'Artículos de aseo gratis',
 'Ascensor',
 'Aseo adicional',
 'Aseo compartido',
 'Balcón',
 'Bar',
 'Bar en la piscina',
 'Bar(No disponible temporalmente)',
 'Barandillas de seguridad para bebés',
 'Barandillas protectoras para bebés',
 'Barbacoa',
 'BarbacoaDe pago',
 'Bañera',
 'Bañera de hidromasaje',
 'Bañera de hidromasaje / jacuzzi',
 'Bañera de hidromasaje / jacuzziDe pago',
 'Bañera o ducha',
 'Baño adicional',
 'Baño al aire libre',
 'Baño al aire libreDe pago',
 'Baño compartido',
 'Baño de vapor',
 'Baño privado',
 'Baño público',
 'Baño públicoDe pago',
 'Baños termales',
 'Bicicletas disponibles (gratis)',
 'Bidet',
 'Billar',
 'BillarDe pago',
 'Bingo',
 'Boles para mascotas',
 'Buffet para niños',
 'Cafetería en el alojamiento',
 'Caja fuerte',
 'Caja fuerte para ordenador portátil',
 'Caja fuerteDe pago',
 'Cajero automático en el hotel',
 'Calefacción',
 'Cama plegable',
 'Camas extralargas (más de 2 metros)',
 'Cambio de moneda',
 'Campo de golf (a menos de 3 km)De pago',
 'Canales de pago',
 'Canales por cable',
 'Canales vía satélite',
 'Canguro / servicios para niños',
 'Canguro / servicios para niñosDe pago',
 'Capilla',
 'Catalán',
 'Cenas temáticas',
 'Cenas temáticasDe pago',
 'Cenas temáticasFuera del alojamiento',
 'Cenas temáticasFuera del alojamientoDe pago',
 'Centro de negocios',
 'Centro de negociosDe pago',
 'Cesta para mascotas',
 'Chimenea exterior',
 'Ciclismo',
 'CiclismoFuera del alojamiento',
 'Clases de cocina',
 'Clases de cocinaDe pago',
 'Clases de cocinaFuera del alojamiento',
 'Clases de cocinaFuera del alojamientoDe pago',
 'Clases de fitness',
 'Clases de yoga',
 'Club infantil',
 'Cochecitos de bebé',
 'Cocina',
 'Cocina compartida',
 'Comedia en vivoDe pago',
 'Corte de pelo',
 'Cubierta para piscina',
 'Cámaras de seguridad en las zonas comunitarias',
 'Cámaras de seguridad fuera del alojamiento',
 'Dardos',
 'De temporada',
 'Desayuno en la habitación',
 'Detector de monóxido de carbono',
 'Detectores de humo',
 'Discoteca / DJ',
 'Discoteca / DJDe pago',
 'Ducha',
 'Enchufe cerca de la cama',
 'Entrada privada',
 'Entrenador personal',
 'Entretenimiento nocturno',
 'Entretenimiento nocturnoDe pago',
 'Envoltura corporal',
 'Equipamiento de bádminton',
 'Equipamiento de juegos para exterior',
 'Equipamiento de tenis',
 'Equipamiento de tenisDe pago',
 'Equipo de planchado',
 'Equitación',
 'EquitaciónDe pago',
 'EquitaciónFuera del alojamiento',
 'EquitaciónFuera del alojamientoDe pago',
 'Escritorio',
 'Español',
 'EsquíFuera del alojamiento',
 'Estación de carga de vehículos eléctricos',
 'Eventos deportivos en directo (emisión)',
 'Eventos deportivos en directo (emisión)De pago',
 'Eventos deportivos en directo (emisión)Fuera del alojamiento',
 'Eventos deportivos en directo (emisión)Fuera del alojamientoDe pago',
 'Exfoliación corporal',
 'Extintores',
 'Fax / fotocopiadora',
 'Fax / fotocopiadoraDe pago',
 'Fogones',
 'Francés',
 'Fruta',
 'FrutaDe pago',
 'Galerías de arte temporales',
 'Galerías de arte temporalesDe pago',
 'Galerías de arte temporalesFuera del alojamiento',
 'Galerías de arte temporalesFuera del alojamientoDe pago',
 'Gimnasio',
 'GimnasioDe pago',
 'Guardaequipaje',
 'GuardaequipajeDe pago',
 'Guyaratí',
 'Habitaciones comunicadas disponibles',
 'Habitaciones familiares',
 'Habitaciones hipoalergénicas',
 'Habitaciones insonorizadas',
 'Habitaciones sin humo',
 'Hammam',
 'Happy hour',
 'Happy hourDe pago',
 'Hebreo',
 'Hervidor eléctrico',
 'Hindi',
 'Hipoalergénico',
 'Holandés',
 'Horario de apertura',
 'Horno',
 'Húngaro',
 'Independiente',
 'Información turística',
 'Inglés',
 'Insonorización',
 'Instalaciones de spa',
 'Instalaciones para deportes acuáticos en el alojamiento',
 'Instalaciones para deportes acuáticos en el alojamientoDe pago',
 'Italiano',
 'Japonés',
 'Jardín',
 'Juegos de mesa / puzles',
 'Juguetes para la piscina',
 'Karaoke',
 'Lavadora',
 'Lavamanos más bajo',
 'Lavavajillas',
 'Libros DVD o música para niños',
 'Llave de acceso',
 'Manicura',
 'Masaje corporal completo',
 'Masaje corporal completoDe pago',
 'Masaje de cabeza',
 'Masaje de cabezaDe pago',
 'Masaje de cuello',
 'Masaje de cuelloDe pago',
 'Masaje de espalda',
 'Masaje de espaldaDe pago',
 'Masaje de manos',
 'Masaje de manosDe pago',
 'Masaje de pies',
 'Masaje de piesDe pago',
 'Masaje en pareja',
 'Masaje en parejaDe pago',
 'Masajes',
 'MasajesDe pago',
 'Menú para niños',
 'Menú para niñosDe pago',
 'Menús para dietas especiales (bajo petición)',
 'Mesa de comedor',
 'Microondas',
 'Minibar',
 'Minigolf',
 'MinigolfDe pago',
 'Mobiliario exterior',
 'Mosquitera',
 'Muebles de exterior',
 'Máquina expendedora (aperitivos)',
 'Máquina expendedora (bebidas)',
 'Música / espectáculos en directo',
 'Música / espectáculos en directoDe pago',
 'Música / espectáculos en directoFuera del alojamiento',
 'Música / espectáculos en directoFuera del alojamientoDe pago',
 'Nevera',
 'Noches de cine',
 'Noches de cineFuera del alojamiento',
 'Noches de cineFuera del alojamientoDe pago',
 'Ordenador',
 'Ordenador portátil',
 'Papel higiénico',
 'Paquetes de spa / bienestar',
 'Para todas las edades',
 'Parking adaptado para personas de movilidad reducida',
 'Parking en la calle',
 'Parking en un garaje',
 'Parking vigilado',
 'Parque acuático',
 'Parque acuáticoDe pago',
 'Parque acuáticoFuera del alojamiento',
 'Parque acuáticoFuera del alojamientoDe pago',
 'Patio',
 'Pedicura',
 'Pediluvio',
 'Peinado',
 'Peluquería / salón de belleza',
 'Perchero',
 'Personal de animación',
 'Pesca',
 'PescaDe pago',
 'PescaFuera del alojamiento',
 'PescaFuera del alojamientoDe pago',
 'Ping pong',
 'Piragüismo',
 'PiragüismoDe pago',
 'PiragüismoFuera del alojamiento',
 'PiragüismoFuera del alojamientoDe pago',
 'Piscina climatizada',
 'Piscina con vistas',
 'Piscina de agua salada',
 'Piscina en la azotea',
 'Piscina infantil',
 'Piscina infinita',
 'Piscina pequeña',
 'Piscina privada',
 'Pista de tenisFuera del alojamiento',
 'Plancha para pantalones',
 'Plancha para pantalonesDe pago',
 'Plancha para ropa',
 'Playa',
 'Polaco',
 'Portugués',
 'Productos de limpieza',
 'Prohibido fumar en todo el alojamiento',
 'Proporciona factura',
 'Protector de enchufes para niños',
 'Radio',
 'Recepción 24 horas',
 'Registro de entrada / salida privado',
 'Registro de entrada y salida exprés',
 'Registro de entrada y salida exprésDe pago',
 'Reloj despertador',
 'Reproductor de CD',
 'Reproductor de DVD',
 'Restaurante',
 'Restaurante(No disponible temporalmente)',
 'Ropa de cama',
 'Rumano',
 'Ruso',
 'Ruta de bares',
 'Ruta de baresDe pago',
 'Sala de juegos',
 'Salas de reuniones / banquetes',
 'Salas de reuniones / banquetesDe pago',
 'Sauna',
 'SaunaDe pago',
 'Secador de pelo',
 'Secadora de ropa',
 'Seguridad 24 horas',
 'Senderismo',
 'SenderismoDe pago',
 'SenderismoFuera del alojamiento',
 'SenderismoFuera del alojamientoDe pago',
 'Servicio de conserjería',
 'Servicio de despertador',
 'Servicio de despertador / alarma',
 'Servicio de entrega de comestibles',
 'Servicio de entrega de comestiblesDe pago',
 'Servicio de habitaciones',
 'Servicio de lavandería',
 'Servicio de lavanderíaDe pago',
 'Servicio de limpieza diario',
 'Servicio de limpieza diarioDe pago',
 'Servicio de limpieza en seco',
 'Servicio de limpieza en secoDe pago',
 'Servicio de planchado',
 'Servicio de planchadoDe pago',
 'Servicio de recogida en el aeropuerto',
 'Servicio de recogida en el aeropuertoDe pago',
 'Servicio de traslado',
 'Servicio de traslado (de pago)',
 'Servicio de traslado al aeropuerto',
 'Servicio de traslado al aeropuertoDe pago',
 'Servicios de belleza',
 'Servicios de depilación',
 'Servicios de maquillaje',
 'Silla de masajes',
 'Situado frente a la playa',
 'Snack-bar',
 'Snorkel',
 'SnorkelDe pago',
 'SnorkelFuera del alojamiento',
 'SnorkelFuera del alojamientoDe pago',
 'Sofá',
 'Sofá cama',
 'Solo para adultos',
 'Solárium',
 'SoláriumDe pago',
 'Sombrillas',
 'SombrillasDe pago',
 'Soporte para iPod',
 'Spa y centro de bienestar',
 'Spa y centro de bienestar(No disponible temporalmente)De pago',
 'Spa y centro de bienestarDe pago',
 'Submarinismo',
 'SubmarinismoDe pago',
 'SubmarinismoFuera del alojamiento',
 'SubmarinismoFuera del alojamientoDe pago',
 'Suelo de baldosa / mármol',
 'Suelo de madera o parquet',
 'Suelo de moqueta',
 'Supermercado pequeño en el alojamiento',
 'TV',
 'TV de pantalla plana',
 'Taquillas',
 'Taquillas en el gimnasio / spa',
 'Tarjeta de acceso',
 'Tarjetas de transporte público',
 'Tarjetas de transporte públicoDe pago',
 'Teléfono',
 'Tendedero',
 'Terapia con luz',
 'Terraza',
 'Terraza / solárium',
 'Tetera / cafetera',
 'Tinte',
 'Toallas',
 'Toallas / sábanas (por un suplemento)',
 'Toallas de playa/piscina',
 'Tobogán de agua',
 'Toda la unidad accesible en silla de ruedas',
 'Toda la unidad en la planta baja',
 'Tostadora',
 'Tour o clase sobre cultura local',
 'Tour o clase sobre cultura localDe pago',
 'Tours a pie',
 'Tours a pieDe pago',
 'Tours en bici',
 'Tours en biciDe pago',
 'Traslado aeropuerto',
 'Traslado aeropuerto (de pago)',
 'Traslado aeropuerto (gratis)',
 'Tratamientos capilares',
 'Tratamientos corporales',
 'Tratamientos faciales',
 'Trona',
 'Tumbonas/sillas de playa',
 'Tumbonas/sillas de playaDe pago',
 'Utensilios de cocina',
 'Valla alrededor de la piscina',
 'Ventilador',
 'Vestidor',
 'Videoconsola Nintendo Wii',
 'Videoconsola PS2',
 'Videoconsola PS3',
 'Vino / champán',
 'Vino / champánDe pago',
 'Vistas',
 'Vistas a la montaña',
 'Vistas a la piscina',
 'Vistas a un lugar de interés',
 'Vistas a un patio interior',
 'Vistas al jardín',
 'Vistas al lago',
 'Vistas al mar',
 'Vídeo',
 'WC',
 'WC con barras de apoyo',
 'WC elevado',
 'WiFi',
 'WiFi de pago',
 'Windsurf',
 'WindsurfDe pago',
 'WindsurfFuera del alojamiento',
 'WindsurfFuera del alojamientoDe pago',
 'Zapatillas',
 'Zona TV / salón de uso compartido',
 'Zona de cocina',
 'Zona de comedor',
 'Zona de comedor exterior',
 'Zona de estar',
 'Zona de fumadores',
 'Zona de juegos interior',
 'Zona de juegos para niños',
 'Zona de pícnic',
 'Zona de spa / relajación',
 'Zona poco profunda',
 'Zona privada de playa',
 'Zona privada de playaDe pago',
 'iPad']

### Servicios heredados

In [26]:
heredados = [
'Baños termales',
'Pesca', 'PescaDe pago', 
'Playa', 'Vistas',
 'Vistas a la montaña', 'Vistas al lago', 'Vistas al mar', 
 'Situado frente a la playa', 
 ]

In [27]:
booking_servicios['heredados'] = bookingOHE[heredados].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0
...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0

In [28]:
booking_servicios['total_heredados'] =  bookingOHE[heredados].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0

### Acceso y comunicación

In [29]:
acceso =[
'Alemán','Alquiler de bicicletas (de pago)', 'Alquiler de coches',
'Bicicletas disponibles (gratis)', 'Catalán', 'Fax / fotocopiadora',
'Fax / fotocopiadoraDe pago', 'Francés', 'Guyaratí', 'Hebreo', 
'Hindi', 'Húngaro', 'Inglés','Italiano', 'Japonés', 'Ordenador', 
'Ordenador portátil','Polaco', 'Portugués', 'Radio', 
'Recepción 24 horas', 'Rumano', 'Ruso', 'Servicio de recogida en el aeropuerto',
'Servicio de recogida en el aeropuertoDe pago', 'Servicio de traslado', 
'Servicio de traslado (de pago)',
'Servicio de traslado al aeropuerto','Servicio de traslado al aeropuertoDe pago',
'Tarjetas de transporte público', 'Tarjetas de transporte públicoDe pago',
'Teléfono', 'Traslado aeropuerto', 'Traslado aeropuerto (de pago)',
'Traslado aeropuerto (gratis)', 'WiFi', 'WiFi de pago', 
]

In [30]:
booking_servicios['acceso/comunicacion'] =  bookingOHE[acceso].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1

In [31]:
booking_servicios['total_acceso/comunicacion'] =  bookingOHE[acceso].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4

### Entretenimiento y deporte

In [32]:
entretenimiento = [
'Aeróbic', 'AeróbicDe pago', 'AeróbicFuera del alojamientoDe pago',
'Canales por cable', 'Canales vía satélite', 'Ciclismo',
'CiclismoFuera del alojamiento', 'Clases de cocina', 'Clases de cocinaDe pago',
'Clases de cocinaFuera del alojamiento', 'Clases de cocinaFuera del alojamientoDe pago',
'Clases de fitness', 'Clases de yoga', 'Comedia en vivoDe pago', 'Discoteca / DJ', 'Discoteca / DJDe pago', 'Entrada privada',
 'Entrenador personal', 'Entretenimiento nocturno', 'Entretenimiento nocturnoDe pago',
'Equipamiento de bádminton', 'Equipamiento de juegos para exterior',
'Equipamiento de tenis', 'Equipamiento de tenisDe pago', 'Equitación',
'EquitaciónDe pago', 'EquitaciónFuera del alojamiento', 'EquitaciónFuera del alojamientoDe pago',
'EsquíFuera del alojamiento','Eventos deportivos en directo (emisión)', 'Eventos deportivos en directo (emisión)De pago', 'Eventos deportivos en directo (emisión)Fuera del alojamiento',
'Eventos deportivos en directo (emisión)Fuera del alojamientoDe pago',
'FrutaDe pago', 'Galerías de arte temporales', 'Galerías de arte temporalesDe pago',
'Galerías de arte temporalesFuera del alojamiento', 'Galerías de arte temporalesFuera del alojamientoDe pago',
'Gimnasio', 'GimnasioDe pago', 'Happy hour', 'Happy hourDe pago',
'Instalaciones para deportes acuáticos en el alojamiento',
'Instalaciones para deportes acuáticos en el alojamientoDe pago',
'Juguetes para la piscina', 'Karaoke', 'Minibar', 'Minigolf', 'MinigolfDe pago',
'Música / espectáculos en directo', 'Música / espectáculos en directoDe pago', 'Música / espectáculos en directoFuera del alojamiento',
'Música / espectáculos en directoFuera del alojamientoDe pago',
'Noches de cine', 'Noches de cineFuera del alojamiento', 'Noches de cineFuera del alojamientoDe pago', 'Parque acuático', 'Parque acuáticoDe pago', 'Parque acuáticoFuera del alojamiento', 'Parque acuáticoFuera del alojamientoDe pago',
'Personal de animación', 'Ping pong', 'Piragüismo',
 'PiragüismoDe pago', 'PiragüismoFuera del alojamiento',
 'PiragüismoFuera del alojamientoDe pago', 'Piscina climatizada',
 'Piscina con vistas', 'Piscina de agua salada', 'Piscina en la azotea',
'Piscina infinita', 'Piscina pequeña', 'Piscina privada',
'Pista de tenisFuera del alojamiento', 'Reproductor de CD',
'Reproductor de DVD', 'Sala de juegos', 'Seguridad 24 horas',
'Senderismo', 'SenderismoDe pago', 'SenderismoFuera del alojamiento',
'SenderismoFuera del alojamientoDe pago', 'Snorkel', 'SnorkelDe pago',
'SnorkelFuera del alojamiento', 'SnorkelFuera del alojamientoDe pago',
'Spa y centro de bienestarDe pago', 'Submarinismo', 'SubmarinismoDe pago',
'SubmarinismoFuera del alojamiento', 'SubmarinismoFuera del alojamientoDe pago', 
'TV', 'TV de pantalla plana',
'Tour o clase sobre cultura local', 'Tour o clase sobre cultura localDe pago',
'Tours a pie', 'Tours a pieDe pago', 'Tours en bici', 'Tours en biciDe pago',
'Windsurf', 'WindsurfDe pago', 'WindsurfFuera del alojamiento',
'WindsurfFuera del alojamientoDe pago',
]

In [33]:
booking_servicios['entretenimiento/deporte'] =  bookingOHE[entretenimiento].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1

In [34]:
booking_servicios['total_entretenimiento/deporte'] =  bookingOHE[entretenimiento].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1

### Inclusión

In [35]:
inclusion = [
'Acceso a pisos superiores en ascensor', 'Adaptado para sillas de ruedas',
'Ascensor','Adaptado personas de movilidad reducida',
'Apoyo visual: braille', 'Apoyo visual: carteles táctiles',  'Parking adaptado para personas de movilidad reducida', 'WC con barras de apoyo',
'WC elevado',
]

In [36]:
booking_servicios['inclusion'] = bookingOHE[inclusion].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7,0
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4,0
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3,1
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5,0
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1,0

In [37]:
booking_servicios['total_inclusion'] =  bookingOHE[inclusion].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1,0,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7,0,0
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1,0,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4,0,0
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4,0,0
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3,0,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3,1,4
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5,0,0
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1,0,0

### Apto para niños

In [38]:
ninios = [
'Adecuada para niños', 'Barandillas de seguridad para bebés',
'Barandillas protectoras para bebés', 'Buffet para niños',
'Canguro / servicios para niños','Canguro / servicios para niñosDe pago',
'Club infantil','Cochecitos de bebé', 'Habitaciones familiares',
'Libros DVD o música para niños', 'Menú para niños', 
'Menú para niñosDe pago', 'Protector de enchufes para niños', 
'Para todas las edades', 'Piscina infantil','Zona de juegos para niños',
]

In [39]:
booking_servicios['ninios'] =  bookingOHE[ninios].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1,0,0,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7,0,0,1
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1,0,0,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4,0,0,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4,0,0,1
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3,0,0,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3,1,4,1
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5,0,0,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1,0,0,1

In [40]:
booking_servicios['total_ninios'] =  bookingOHE[ninios].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1,0,0,0,0
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7,0,0,1,3
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1,0,0,0,0
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4,0,0,1,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4,0,0,1,1
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3,0,0,0,0
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3,1,4,1,2
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5,0,0,1,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1,0,0,1,1

### Comida

In [41]:
comida = [
'Almuerzos para llevar', 'Bar', 'Bar en la piscina',
'Bar(No disponible temporalmente)', 'Barbacoa',
'BarbacoaDe pago', 'Cafetería en el alojamiento',
'Catalán', 'Cenas temáticas', 'Cenas temáticasDe pago',
'Cenas temáticasFuera del alojamiento', 'Cenas temáticasFuera del alojamientoDe pago',
'Cocina', 'Cocina compartida', 'Desayuno en la habitación',
'Fruta', 'FrutaDe pago', 'Horno','Menús para dietas especiales (bajo petición)',
'Microondas', 'Minibar', 'Máquina expendedora (aperitivos)',
'Máquina expendedora (bebidas)',  'Zona de pícnic',
]

In [42]:
booking_servicios['comida/bebida'] =  bookingOHE[comida].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,1,1,2,1,1,0,0,0,0,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,2,1,6,1,7,0,0,1,3,1
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,0,1,2,1,1,0,0,0,0,1
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,2,1,1,1,4,0,0,1,1,1
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,0,1,1,1,4,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,0,1,2,1,4,0,0,1,1,1
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,0,1,2,1,3,0,0,0,0,1
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,0,1,5,1,3,1,4,1,2,0
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,2,1,7,1,5,0,0,1,1,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,0,1,4,1,1,0,0,1,1,1

In [43]:
booking_servicios['total_comida/bebida'] =  bookingOHE[comida].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,...,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida,total_comida/bebida
164,Bacalar,166,Habitas Bacalar,5977,8.8,9.5,5,1,1,1,...,1,2,1,1,0,0,0,0,1,1
114,Bacalar,10,XO Hotel Bacalar Lakefront - All Inclusive,2745,7.2,7.1,3,2,2,1,...,1,6,1,7,0,0,1,3,1,7
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,3,3,0,...,1,2,1,1,0,0,0,0,1,2
116,Bacalar,367,Blue Bird,2964,7.9,8.7,0,4,4,1,...,1,1,1,4,0,0,1,1,1,4
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,5,5,0,...,1,1,1,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,926,528,0,...,1,2,1,4,0,0,1,1,1,2
529,Tulum,11,Loft open space Tulum,1165,8.6,8.5,3,927,529,0,...,1,2,1,3,0,0,0,0,1,1
530,Tulum,83,Tulum Nah,802,8.6,8.3,3,928,530,0,...,1,5,1,3,1,4,1,2,0,0
531,Tulum,193,Casa Ganesh Tulum,4080,8.0,8.3,0,929,531,1,...,1,7,1,5,0,0,1,1,1,1
532,Tulum,10,Casa Bohemia,797,8.4,7.6,0,930,532,0,...,1,4,1,1,0,0,1,1,1,1

In [44]:
booking_servicios.describe()

,prices,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida,total_comida/bebida
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,2391.791988,8.305855,2.175655,457.249615,183.861325,0.363636,0.664099,0.938367,3.465331,0.927581,5.395994,0.232666,0.403698,0.676425,1.110940,0.795069,2.357473
std,3047.984524,0.920076,1.805331,291.771789,173.669348,0.481417,1.000597,0.240674,2.498601,0.259381,4.484065,0.422857,0.911375,0.468201,1.039358,0.403962,2.147733
min,159.000000,1.300000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,976.000000,7.900000,0.000000,199.000000,34.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,1531.000000,8.400000,3.000000,437.000000,107.000000,0.000000,0.000000,1.000000,3.000000,1.000000,4.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000
75%,2650.000000,8.900000,4.000000,746.000000,348.000000,1.000000,1.000000,1.000000,5.000000,1.000000,7.000000,0.000000,0.000000,1.000000,2.000000,1.000000,4.000000
max,51797.000000,10.000000,5.000000,930.000000,532.000000,1.000000,4.000000,1.000000,11.000000,1.000000,34.000000,1.000000,6.000000,1.000000,7.000000,1.000000,13.000000

In [45]:
booking_servicios.to_csv('./data/booking_servicios_sumas_clasificados.csv',index=False)

# Trip Advisor

In [46]:
trip = pd.read_csv('./tripadvisor/tripadvisorSolPlaya.csv')
trip

,city,comments,name,prices,quality_price,rating,services,stars,url
0,Isla Mujeres,100 opiniones,"Icaco Island Village Apartamento, Isla Mujeres",NaN,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1,Riviera Nayarit,3 opiniones,"Ximena Hotel Boutique, Sayulita, Nayarit",NaN,NaN,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g4...
2,Isla Mujeres,7 opiniones,Ocean Drive Hotel - Isla Mujeres,NaN,NaN,2.5,"Estacionamiento público gratuito cercano,Wifi,...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
3,Isla Mujeres,3 opiniones,"Hotel Maria Elena, Isla Mujeres",NaN,NaN,4.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
4,Isla Mujeres,105 opiniones,"Chichi's 'n Charlies Rancho, Isla Mujeres",NaN,ui_bubble_rating bubble_40,3.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
...,...,...,...,...,...,...,...,...,...
1497,Todos Santos,9 opiniones,"Osprey San Pedrito Villa vacacional, Todos San...",NaN,ui_bubble_rating bubble_50,5.0,Playa,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1498,Todos Santos,295 opiniones,"Arriba de la Roca, Todos Santos, Baja California",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1499,Todos Santos,26 opiniones,"CalyCanto Casitas Villa vacacional, Todos Sant...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1500,Todos Santos,46 opiniones,"Flora del Mar Posada, Todos Santos, Baja Calif...",NaN,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1501,Todos Santos,NaN,"Jardin de Pilar Rancho, Todos Santos, Baja Cal...",NaN,NaN,NaN,NaN,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...

In [47]:
trip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1502 entries, 0 to 1501
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           1502 non-null   object
 1   comments       1123 non-null   object
 2   name           1502 non-null   object
 3   prices         182 non-null    object
 4   quality_price  734 non-null    object
 5   rating         1123 non-null   float64
 6   services       994 non-null    object
 7   stars          411 non-null    object
 8   url            1502 non-null   object
dtypes: float64(1), object(8)
memory usage: 105.7+ KB

In [48]:
trip.sort_values('city',inplace=True)

In [49]:
trip['id'] = np.arange(trip.shape[0]) + 1

In [50]:
trip['rank'] = np.int64(trip.groupby('city')['id'].rank('first'))

In [51]:
trip

,city,comments,name,prices,quality_price,rating,services,stars,url,id,rank
235,Ayotoxco,63 opiniones,Rancho El Paraiso de Ayotoxco Estancia,NaN,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet gratuito,Pisci...",2.5 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g5...,1,1
1444,B & B y posadas de Puerto Vallarta,334 opiniones,"Quinta Maria Cortez B & B, Puerto Vallarta, Ja...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...,2,1
1448,B & B y posadas de Puerto Vallarta,456 opiniones,"Hacienda Alemana Boutique Hotel Posada, Puerto...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...,3,2
1455,B & B y posadas de Puerto Vallarta,240 opiniones,"Villa Lola B & B, Puerto Vallarta, Jalisco",NaN,ui_bubble_rating bubble_50,5.0,"Internet de alta velocidad gratuito (WiFi),Pis...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...,4,3
1456,B & B y posadas de Puerto Vallarta,855 opiniones,"Garlands Del Rio Boutique Hotel B & B, Puerto ...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento público pagado en el predio,In...",4.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...,5,4
...,...,...,...,...,...,...,...,...,...,...,...
1476,Todos Santos,3 opiniones,"Gypsy Canyon Alojamiento, Todos Santos, Baja C...",NaN,NaN,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...,1498,39
1477,Todos Santos,3 opiniones,"Alegria Posada, Todos Santos, Baja California",NaN,NaN,4.5,NaN,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...,1499,40
1446,Todos Santos,245 opiniones,"Los Colibris Casitas Villa vacacional, Todos S...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...,1500,41
1501,Todos Santos,NaN,"Jardin de Pilar Rancho, Todos Santos, Baja Cal...",NaN,NaN,NaN,NaN,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...,1501,42
66,Zacatlán,16 opiniones,"Mountain Lodge, Zacatlán, Puebla",NaN,NaN,5.0,"Internet de alta velocidad gratuito (WiFi),Ser...",2.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g2...,1502,1

In [52]:
trip.dropna(subset=["prices"],inplace=True)
trip.drop("url",axis=1,inplace=True)

## Comments

In [53]:
trip.comments = trip.comments.apply(lambda x: int(str(x.split()[0]).replace(",","")) if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,"Zensus, Bacalar, Quintana Roo","$1,566,$1,566,$1,566",NaN,5.0,NaN,NaN,107,102
1132,Bacalar,122,"Casa Lamat, Bacalar, Quintana Roo","$1,234,$1,240,$1,234",ui_bubble_rating bubble_35,4.0,"Estacionamiento gratis,Internet gratuito,Playa...",NaN,109,104
1134,Bacalar,99,"Amigos Hotelito, Bacalar, Quintana Roo","$1,800,$1,800",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,111,106
1135,Bacalar,737,"Centro Holistico Akalki Spa, Bacalar, Quintana...","$7,612",ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,112,107
1136,Bacalar,62,"Bacalar Sunrise Villa Alojamiento, Quintana Roo","$1,461,$1,264",ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,"Perro Surfero Boutique Hotel B & B, Todos Sant...","$2,199,$2,826,$2,812",ui_bubble_rating bubble_50,4.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,1483,24
1418,Todos Santos,429,"Guaycura Boutique Hotel Beach Club & Spa, Todo...","$4,477,$4,477,$4,477,$4,499,$4,477,$4,478",ui_bubble_rating bubble_45,4.5,"Internet de alta velocidad gratuito (WiFi),Pis...",3.5 de 5 burbujas,1484,25
1417,Todos Santos,95,"Paradero Todos Santos Hotel, Baja California","$12,756,$12,756,$12,756,$12,756,$12,760,$12,756",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,1485,26
1416,Todos Santos,104,"La Bohemia Baja Hotel Pequeno, Todos Santos, B...","$2,904",ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,1486,27
1414,Todos Santos,123,"Serendipity B & B, Todos Santos, Baja California","$3,387,$3,387",ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",5.0 de 5 burbujas,1488,29

## Name

In [54]:
trip.name = trip.name.apply(lambda x: x.split(",")[0])
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,"$1,566,$1,566,$1,566",NaN,5.0,NaN,NaN,107,102
1132,Bacalar,122,Casa Lamat,"$1,234,$1,240,$1,234",ui_bubble_rating bubble_35,4.0,"Estacionamiento gratis,Internet gratuito,Playa...",NaN,109,104
1134,Bacalar,99,Amigos Hotelito,"$1,800,$1,800",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,"$7,612",ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,"$1,461,$1,264",ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,"$2,199,$2,826,$2,812",ui_bubble_rating bubble_50,4.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,"$4,477,$4,477,$4,477,$4,499,$4,477,$4,478",ui_bubble_rating bubble_45,4.5,"Internet de alta velocidad gratuito (WiFi),Pis...",3.5 de 5 burbujas,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,"$12,756,$12,756,$12,756,$12,756,$12,760,$12,756",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,"$2,904",ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,1486,27
1414,Todos Santos,123,Serendipity B & B,"$3,387,$3,387",ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",5.0 de 5 burbujas,1488,29

## Prices

In [55]:
trip.prices = trip.prices.apply(lambda x: x.replace(",$"," # ").replace("$","").replace(",","") if str(x)!="nan" else np.nan)
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,NaN,5.0,NaN,NaN,107,102
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,ui_bubble_rating bubble_35,4.0,"Estacionamiento gratis,Internet gratuito,Playa...",NaN,109,104
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,ui_bubble_rating bubble_50,4.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,ui_bubble_rating bubble_45,4.5,"Internet de alta velocidad gratuito (WiFi),Pis...",3.5 de 5 burbujas,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,ui_bubble_rating bubble_50,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,1486,27
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",5.0 de 5 burbujas,1488,29

## Quality price

In [56]:
trip.quality_price = trip.quality_price.apply(lambda x: int(x.split("_")[-1])/10 if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,0.0,5.0,NaN,NaN,107,102
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,3.5,4.0,"Estacionamiento gratis,Internet gratuito,Playa...",NaN,109,104
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,4.0,4.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,5.0,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,"Internet de alta velocidad gratuito (WiFi),Pis...",3.5 de 5 burbujas,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,1486,27
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,5.0,5.0,"Estacionamiento gratis,Internet de alta veloci...",5.0 de 5 burbujas,1488,29

## Services

In [57]:
trip.services = trip.services.apply(lambda x: x.replace(","," # ") if str(x)!="nan" else "")
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,0.0,5.0,,NaN,107,102
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,3.5,4.0,Estacionamiento gratis # Internet gratuito # P...,NaN,109,104
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,NaN,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,Estacionamiento gratis # Internet de alta velo...,NaN,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,NaN,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,Internet de alta velocidad gratuito (WiFi) # W...,NaN,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,Internet de alta velocidad gratuito (WiFi) # P...,3.5 de 5 burbujas,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,NaN,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,3.0 de 5 burbujas,1486,27
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,5.0,5.0,Estacionamiento gratis # Internet de alta velo...,5.0 de 5 burbujas,1488,29

## Stars

In [58]:
trip.stars = trip.stars.apply(lambda x: x.split()[0] if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,0.0,5.0,,0,107,102
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,3.5,4.0,Estacionamiento gratis # Internet gratuito # P...,0,109,104
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,0,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,Estacionamiento gratis # Internet de alta velo...,0,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,0,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,Internet de alta velocidad gratuito (WiFi) # W...,0,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,Internet de alta velocidad gratuito (WiFi) # P...,3.5,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,0,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,3.0,1486,27
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,5.0,5.0,Estacionamiento gratis # Internet de alta velo...,5.0,1488,29

In [59]:
trip = trip[trip.city.isin(PM)]
trip

,city,comments,name,prices,quality_price,rating,services,stars,id,rank
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,0.0,5.0,,0,107,102
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,3.5,4.0,Estacionamiento gratis # Internet gratuito # P...,0,109,104
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,0,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,Estacionamiento gratis # Internet de alta velo...,0,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,0,113,108
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,Internet de alta velocidad gratuito (WiFi) # W...,0,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,Internet de alta velocidad gratuito (WiFi) # P...,3.5,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,0,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,3.0,1486,27
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,5.0,5.0,Estacionamiento gratis # Internet de alta velo...,5.0,1488,29

In [60]:
trip = trip.drop_duplicates()

In [61]:
trip.to_csv('./data/trip_clean.csv')

In [62]:
tripOHE = trip.drop("services",axis=1).join(trip.services.str.get_dummies(sep=" # "))
tripOHE

,city,comments,name,prices,quality_price,rating,stars,id,rank,DVD,...,Tienda de regalos,Transporte al aeropuerto,Utensilios de cocina,Vista a la ciudad,Vista a la montaña,Vista a la piscina,Vista a un lugar de interés,Vista al mar,Wifi,Wifi público
1130,Bacalar,9,Zensus,1566 # 1566 # 1566,0.0,5.0,0,107,102,0,...,0,0,0,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234 # 1240 # 1234,3.5,4.0,0,109,104,0,...,0,0,0,0,0,0,0,0,0,0
1134,Bacalar,99,Amigos Hotelito,1800 # 1800,4.0,4.0,0,111,106,0,...,0,0,0,0,0,0,0,0,0,0
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,0,...,0,0,0,0,0,0,0,1,0,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461 # 1264,5.0,4.5,0,113,108,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,0,1483,24,0,...,0,0,0,0,0,0,0,0,1,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,3.5,1484,25,0,...,0,0,0,0,0,0,0,0,0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,0,1485,26,0,...,0,1,0,0,0,0,0,0,0,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,...,0,1,0,0,0,0,0,0,0,0
1414,Todos Santos,123,Serendipity B & B,3387 # 3387,5.0,5.0,5.0,1488,29,0,...,0,0,0,0,0,0,0,1,0,0

In [63]:
tripOHE.prices = trip.prices.apply(lambda x: int(x.split("#")[0]) if str(x)!="nan" else np.nan)
tripOHE

,city,comments,name,prices,quality_price,rating,stars,id,rank,DVD,...,Tienda de regalos,Transporte al aeropuerto,Utensilios de cocina,Vista a la ciudad,Vista a la montaña,Vista a la piscina,Vista a un lugar de interés,Vista al mar,Wifi,Wifi público
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,...,0,0,0,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,0,...,0,0,0,0,0,0,0,0,0,0
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,0,...,0,0,0,0,0,0,0,0,0,0
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,0,...,0,0,0,0,0,0,0,1,0,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,...,0,0,0,0,0,0,0,0,1,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,0,...,0,0,0,0,0,0,0,0,0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,...,0,1,0,0,0,0,0,0,0,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,...,0,1,0,0,0,0,0,0,0,0
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,0,...,0,0,0,0,0,0,0,1,0,0

In [64]:
tripOHE.to_csv('./data/tripadvisorSolPlaya_OHE.csv',index=False)

## Reducción de servicios en categorías:
+ **Heredados** Aquellos que provienen de recursos naturales
+ **Acceso y comunicación** Aquellos que permiten una comunicación al huésped, como el habla de idiomas extranjeros, wifi, teléfono, transporte, etc.
+ **Entretenimiento** Actividades extras dentro y fuera del hotel.
+ **Inclusión** Aquellos servicios que tienen en cuenta a personas algún tipo de discapacidad.
+ **Apto para infantes** Servicios que indican la inclusión de niños.
+ **Restaurante/Bar** Servicios en relación a la comida y bebidas.
+ **~Pet Friendly** Si las mascotas son permitidas o no dentro del hotel

In [65]:
trip_servicios = tripOHE[tripOHE.columns[:9]].copy()
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108
...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29

In [66]:
list(tripOHE.columns[7:])

['id',
 'rank',
 ' DVD',
 ' música para niños',
 'Actividades infantiles (Ideal para niños / familias)',
 'Aire acondicionado',
 'Almacenamiento de equipaje',
 'Alquiler de bicicletas',
 'Balcón privado',
 'Bar/Salón',
 'Batas de baño',
 'Bañera con hidromasaje',
 'Bañera de hidromasaje',
 'Bañera/Ducha',
 'Baño adicional',
 'Baños privados',
 'Bicicletas disponibles',
 'Botellas de agua',
 'Buceo',
 'Cadenas de televisión para niños',
 'Cafetería',
 'Café instantáneo gratis',
 'Caja fuerte',
 'Camas extralargas',
 'Cambio de divisas',
 'Campo de golf',
 'Canotaje',
 'Centro de negocios con acceso a Internet',
 'Check-in y check-out exprés',
 'Clases de yoga',
 'Cocina',
 'Comedor',
 'Conserje',
 'Cortinas blackout',
 'Desayuno disponible',
 'Desayuno gratis',
 'Ducha a ras de suelo',
 'Equipo para niños para jugar al aire libre',
 'Escritorio',
 'Esnórquel',
 'Estacionamiento',
 'Estacionamiento en la calle',
 'Estacionamiento gratis',
 'Estacionamiento gratuito privado cercano',
 'Estacionamiento privado pagado cercano',
 'Estacionamiento público gratuito cercano',
 'Estacionamiento vigilado',
 'Estante para la ropa',
 'Excursionismo',
 'Fotocopiadora/Fax en el centro de negocios',
 'Garaje de estacionamientos',
 'Gimnasio / Sala de entrenamiento',
 'Guardarropa/Ropero',
 'Guardería',
 'Habitaciones insonorizadas',
 'Habitaciones interconectadas disponibles',
 'Habitaciones para familias',
 'Habitaciones para fumadores disponibles',
 'Habitaciones para no fumadores',
 'Habitación libre de alérgenos',
 'Hotel para no fumadores',
 'Instalaciones para conferencias',
 'Instalaciones para hacer parrillas',
 'Internet',
 'Internet de alta velocidad gratuito (WiFi)',
 'Internet gratuito',
 'Juegos de mesa/Rompecabezas',
 'Kit de primeros auxilios',
 'Kitchenette',
 'Libros',
 'Limpieza en seco',
 'Los niños se alojan gratis',
 'Masaje',
 'Masaje de cuerpo completo',
 'Masaje en pareja',
 'Microondas',
 'Minibar',
 'Muebles de exterior',
 'Máquina de café/té',
 'Navegación',
 'Patio de juegos para niños',
 'Pesca',
 'Piscina',
 'Piscina al aire libre',
 'Piscina en la terraza',
 'Piscina infinita',
 'Piscina para niños',
 'Piso de azulejos/mármol',
 'Plancha',
 'Playa',
 'Playa privada',
 'Productos de tocador de cortesía',
 'Recepción disponible las 24\xa0horas',
 'Red para mosquitos',
 'Refrigerador',
 'Restaurante',
 'Sala de estar',
 'Sala de juegos',
 'Salas de reuniones',
 'Salón de banquetes',
 'Sauna',
 'Se admiten mascotas ( Se aceptan perros / mascotas )',
 'Secador de pelo',
 'Seguridad las 24\xa0horas',
 'Servicio a la habitación',
 'Servicio de despertador/Reloj despertador',
 'Servicio de lavandería',
 'Servicio de limpieza',
 'Servicio de taxi',
 'Sillitas altas disponibles',
 'Solo para adultos',
 'Solárium',
 'Sombrillas',
 'Spa',
 'Suite nupcial',
 'Suites',
 'TV pantalla plana',
 'TV por cable/satélite',
 'Terraza en la azotea',
 'Tienda de regalos',
 'Transporte al aeropuerto',
 'Utensilios de cocina',
 'Vista a la ciudad',
 'Vista a la montaña',
 'Vista a la piscina',
 'Vista a un lugar de interés',
 'Vista al mar',
 'Wifi',
 'Wifi público']

### Heredados

In [67]:
heredados_t = [
'Pesca','Playa','Playa privada', 
'Vista a la montaña', 'Vista al mar',
]

In [68]:
trip_servicios['heredados'] =  tripOHE[heredados_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0
...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1

In [69]:
trip_servicios['total_heredados'] = tripOHE[heredados_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2

### Acceso y comunicación

In [70]:
acceso_t = [
'Alquiler de bicicletas',
'Bicicletas disponibles', 'Internet',
'Internet de alta velocidad gratuito (WiFi)',
'Internet gratuito', 'Servicio de taxi',
 'Transporte al aeropuerto',
'Wifi',
'Wifi público'
]

In [71]:
trip_servicios['acceso/comunicacion'] = tripOHE[acceso_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1

In [72]:
trip_servicios['total_acceso/comunicacion'] = tripOHE[acceso_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1

### Entretenimiento

In [73]:
entretenimiento_t = [
' DVD', 'Campo de golf',
 'Canotaje',
'Clases de yoga',
'Excursionismo', 'Gimnasio / Sala de entrenamiento',
'Juegos de mesa/Rompecabezas',
'Libros', 'Piscina',
'Piscina al aire libre',
'Piscina en la terraza', 'Piscina infinita',
'Sala de juegos',
'TV pantalla plana',
'TV por cable/satélite'
]

In [74]:
trip_servicios['entretenimiento/deporte'] = tripOHE[entretenimiento_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1

In [75]:
trip_servicios['total_entretenimiento/deporte'] = tripOHE[entretenimiento_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0,0
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0,0
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1,3
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1,2
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1,1
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1,1

## Inclusión
Dentro de los servicios que toman en cuenta, no especifican ninguno relacionado a la inclusión de personas con alguna discapacidad.

### Niños

In [76]:
ninios_t = [
' música para niños',
'Actividades infantiles (Ideal para niños / familias)',
'Cadenas de televisión para niños',
'Equipo para niños para jugar al aire libre',
'Guardería', 'Habitaciones para familias',
'Los niños se alojan gratis', 'Patio de juegos para niños',
'Piscina para niños'
]

In [77]:
trip_servicios['ninios'] = tripOHE[ninios_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0,0,1
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0,0,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1,3,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1,2,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1,1,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1,1,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1,1,1

In [78]:
trip_servicios['total_ninios'] = tripOHE[ninios_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0,0,1,1
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0,0,1,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1,1,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1,3,1,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1,2,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1,1,0,0
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1,1,1,2
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1,1,1,2

### Comida

In [79]:
comida_t = [
'Bar/Salón',
'Cafetería', 'Café instantáneo gratis',
'Cocina', 'Comedor', 'Desayuno disponible',
'Desayuno gratis', 'Kitchenette',
'Microondas', 'Minibar', 'Máquina de café/té',
'Refrigerador',
'Restaurante', 
]

In [80]:
trip_servicios['comida/bebida'] = tripOHE[comida_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0,0,1,1,0
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0,0,1,1,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1,1,1,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1,2,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1,3,1,1,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1,2,1,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1,1,0,0,1
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1,1,1,2,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1,1,1,2,1

In [81]:
trip_servicios['total_comida/bebida'] = tripOHE[comida_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida,total_comida/bebida
1130,Bacalar,9,Zensus,1566,0.0,5.0,0,107,102,0,0,0,0,0,0,0,0,0,0
1132,Bacalar,122,Casa Lamat,1234,3.5,4.0,0,109,104,1,1,1,2,0,0,1,1,0,0
1134,Bacalar,99,Amigos Hotelito,1800,4.0,4.0,0,111,106,1,1,1,2,0,0,1,1,1,1
1135,Bacalar,737,Centro Holistico Akalki Spa,7612,4.0,4.5,0,112,107,1,1,1,2,1,1,1,1,1,1
1136,Bacalar,62,Bacalar Sunrise Villa Alojamiento,1461,5.0,4.5,0,113,108,0,0,1,2,1,2,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,1483,24,0,0,1,2,1,3,1,1,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1484,25,1,1,1,2,1,2,1,1,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,1485,26,0,0,1,2,1,1,0,0,1,3
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,1486,27,0,0,1,2,1,1,1,2,1,1
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1488,29,1,2,1,1,1,1,1,2,1,3

In [82]:
trip_servicios.describe()

,comments,prices,quality_price,rating,id,rank,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida,total_comida/bebida
count,83.000000,83.000000,83.000000,76.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000
mean,120.060241,2078.048193,2.777108,4.210526,360.951807,129.156627,0.253012,0.409639,0.674699,1.265060,0.506024,0.951807,0.578313,0.843373,0.578313,1.132530
std,208.313340,1791.305668,2.117369,0.639078,352.641838,74.315163,0.437381,0.812046,0.471335,1.025104,0.503003,1.198613,0.496831,0.876272,0.496831,1.276152
min,0.000000,562.000000,0.000000,1.500000,107.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.500000,1097.000000,0.000000,4.000000,140.500000,69.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,33.000000,1584.000000,4.000000,4.500000,208.000000,127.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,125.500000,2354.000000,4.500000,4.500000,493.000000,192.500000,0.500000,0.500000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000
max,1019.000000,12756.000000,5.000000,5.000000,1488.000000,265.000000,1.000000,3.000000,1.000000,4.000000,1.000000,5.000000,1.000000,3.000000,1.000000,5.000000

In [83]:
trip_servicios.to_csv('./data/trip_servicios_sumas_clasificados.csv',index=False)