In [ ]:
! mkdir data

In [1]:
import numpy as np
import pandas as pd

# Booking

In [2]:
booking = pd.read_csv('./booking/bookingSolPlaya.csv', decimal=',')
booking

,airports,beaches,city,comments,name,popular_services,prices,quality_price,rating,services,stars,url
0,NaN,NaN,"\nMéxico\n,\nNayarit\n,\nCompostela\n",64 comentarios,\nJARDIN DE ESTRELLAS\n,NaN,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4,https://www.booking.com/hotel/mx/jardin-de-est...
1,NaN,NaN,"\nMéxico\n,\nCampeche\n,\nIsla Aguada\n",235 comentarios,"\nFreedom Shores ""La Gringa"" Hotel - Universal...",NaN,"\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3,https://www.booking.com/hotel/mx/freedom-shore...
2,NaN,NaN,"\nTodas las opciones de apartahoteles\n,\nMéxi...",14 comentarios,\nHOTEL CANTO\n,NaN,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3,https://www.booking.com/hotel/mx/canto-bacalar...
3,NaN,NaN,"\nMéxico\n,\nQuintana Roo\n,\nBacalar\n",NaN,\n,NaN,"\nMXN 900\n,\nMXN 800\n,\nMXN 1,100\n,\nMXN 1,...",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0,https://www.booking.com/hotel/mx/catedral-baca...
4,NaN,NaN,"\nMéxico\n,\nQuintana Roo\n,\nBacalar\n",21 comentarios,\nCabañas Colibrí\n,NaN,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3,https://www.booking.com/hotel/mx/cabanas-colib...
...,...,...,...,...,...,...,...,...,...,...,...,...
937,NaN,NaN,\nTodas las opciones de habitaciones en casas ...,NaN,\n,NaN,"\nMXN 1,058\n",NaN,NaN,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0,https://www.booking.com/hotel/mx/habitacion-ta...
938,NaN,NaN,"\nTodas las opciones de villas\n,\nMéxico\n,\n...",NaN,\nCASA BODHI TULUM -city villa with pool-\n,NaN,"\nMXN 5,977\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,https://www.booking.com/hotel/mx/casa-wabi-tul...
939,NaN,NaN,"\nTodas las opciones de apartamentos\n,\nMéxic...",4 comentarios,\nTaanah Poolview 1BR apartment Ecochic\n,NaN,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0,https://www.booking.com/hotel/mx/taanah-poolvi...
940,NaN,NaN,"\nTodas las opciones de apartamentos\n,\nMéxic...",NaN,\nBlue Luxury 1 BD Apartment - Direct exit to ...,NaN,"\nMXN 1,360\n",NaN,NaN,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",4,https://www.booking.com/hotel/mx/blue-luxury-b...
941,NaN,NaN,"\nTodas las opciones de villas\n,\nMéxico\n,\n...",3 comentarios,\nBIT TULUM Villas\n,NaN,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4,https://www.booking.com/hotel/mx/bit-tulum.es....

In [3]:
booking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airports          0 non-null      float64
 1   beaches           0 non-null      float64
 2   city              942 non-null    object
 3   comments          690 non-null    object
 4   name              942 non-null    object
 5   popular_services  0 non-null      float64
 6   prices            942 non-null    object
 7   quality_price     690 non-null    object
 8   rating            690 non-null    float64
 9   services          942 non-null    object
 10  stars             942 non-null    int64
 11  url               942 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 88.4+ KB

In [4]:
booking.drop(['airports', 'beaches','popular_services','url'],axis=1,inplace=True)

In [5]:
booking.dropna(inplace=True)

## City

In [6]:
booking.city = booking.city.apply(lambda x: str(x).replace(",","\n").strip().split("\n")[-1])
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64 comentarios,\nJARDIN DE ESTRELLAS\n,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235 comentarios,"\nFreedom Shores ""La Gringa"" Hotel - Universal...","\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14 comentarios,\nHOTEL CANTO\n,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
4,Bacalar,21 comentarios,\nCabañas Colibrí\n,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
6,Bacalar,15 comentarios,\nCasa baklahar frente a Laguna\n,\nMXN 916\n,6.8,6.5,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
...,...,...,...,...,...,...,...,...
930,Tulum,9 comentarios,\nJungla 22 aldea tulum\n,"\nMXN 974\n,\nMXN 984\n,\nMXN 1,036\n,\nMXN 963\n",4.7,4.3,"\n,\n,\n,\n,\n,\nHorno\n,\n,\n,\n,\n,\n,\n,\n,...",0
931,Tulum,3 comentarios,\n☆Amazing PH Suk Ha☆ La Veleta\n,"\nMXN 3,138\n",9.2,9.3,"\n,\n,\n,\n,\n,\nSecadora de ropa\n,\n,\n,\n,\...",0
932,Tulum,6 comentarios,\nCien Corazones\n,"\nMXN 7,172\n",9.2,9.8,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
939,Tulum,4 comentarios,\nTaanah Poolview 1BR apartment Ecochic\n,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
941,Tulum,3 comentarios,\nBIT TULUM Villas\n,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

## Comments

In [7]:
booking.comments = booking.comments.apply(lambda x: x.split()[0] if str(x)!="nan" else 0)
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,\nJARDIN DE ESTRELLAS\n,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235,"\nFreedom Shores ""La Gringa"" Hotel - Universal...","\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14,\nHOTEL CANTO\n,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
4,Bacalar,21,\nCabañas Colibrí\n,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
6,Bacalar,15,\nCasa baklahar frente a Laguna\n,\nMXN 916\n,6.8,6.5,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
...,...,...,...,...,...,...,...,...
930,Tulum,9,\nJungla 22 aldea tulum\n,"\nMXN 974\n,\nMXN 984\n,\nMXN 1,036\n,\nMXN 963\n",4.7,4.3,"\n,\n,\n,\n,\n,\nHorno\n,\n,\n,\n,\n,\n,\n,\n,...",0
931,Tulum,3,\n☆Amazing PH Suk Ha☆ La Veleta\n,"\nMXN 3,138\n",9.2,9.3,"\n,\n,\n,\n,\n,\nSecadora de ropa\n,\n,\n,\n,\...",0
932,Tulum,6,\nCien Corazones\n,"\nMXN 7,172\n",9.2,9.8,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
939,Tulum,4,\nTaanah Poolview 1BR apartment Ecochic\n,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
941,Tulum,3,\nBIT TULUM Villas\n,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

## Name

In [8]:
booking.name = booking.name.apply(lambda x: x.strip())
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,JARDIN DE ESTRELLAS,"\nMXN 850\n,\nMXN 1,250\n,\nMXN 1,250\n",9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...","\nMXN 990\n,\nMXN 1,090\n,\nMXN 1,190\n,\nMXN ...",7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14,HOTEL CANTO,"\nMXN 750\n,\nMXN 950\n",7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
4,Bacalar,21,Cabañas Colibrí,"\nMXN 1,138\n,\nMXN 1,264\n,\nMXN 1,277\n,\nMX...",7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
6,Bacalar,15,Casa baklahar frente a Laguna,\nMXN 916\n,6.8,6.5,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,"\nMXN 974\n,\nMXN 984\n,\nMXN 1,036\n,\nMXN 963\n",4.7,4.3,"\n,\n,\n,\n,\n,\nHorno\n,\n,\n,\n,\n,\n,\n,\n,...",0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,"\nMXN 3,138\n",9.2,9.3,"\n,\n,\n,\n,\n,\nSecadora de ropa\n,\n,\n,\n,\...",0
932,Tulum,6,Cien Corazones,"\nMXN 7,172\n",9.2,9.8,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,"\nMXN 1,694\n",8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
941,Tulum,3,BIT TULUM Villas,"\nMXN 2,671\n,\nMXN 2,873\n",7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

## Prices

In [9]:
booking.prices = booking.prices.apply(lambda x: x.replace("MXN","").replace(",","").replace("\n\n","\n").strip().replace("\n"," #"))
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,JARDIN DE ESTRELLAS,850 # 1250 # 1250,9.3,9.4,"\n,\n,\n,\n,\n,\nBaño privado\n,\n,\n,\n,\n,\n...",4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990 # 1090 # 1190 # 850 # 990 # 1090 # 1190 # ...,7.7,8.0,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
2,Bacalar,14,HOTEL CANTO,750 # 950,7.9,7.7,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",3
4,Bacalar,21,Cabañas Colibrí,1138 # 1264 # 1277 # 1419 # 1457 # 1589 # 1637...,7.3,7.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",3
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,"\n,\n,\n,\n,\n,\nPapel higiénico\n,\n,\n,\n,\n...",0
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974 # 984 # 1036 # 963,4.7,4.3,"\n,\n,\n,\n,\n,\nHorno\n,\n,\n,\n,\n,\n,\n,\n,...",0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,"\n,\n,\n,\n,\n,\nSecadora de ropa\n,\n,\n,\n,\...",0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,"\n,\n,\n,\n,\n,\nAbierta todo el año\n,\n,\n,\...",0
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,"\n,\n,\n,\n,\n,\nMesa de comedor\n,\n,\n,\n,\n...",4

## Services

In [10]:
booking.services = booking.services.apply(lambda x: " # ".join(x.replace(",","").strip().replace("\n",";").split(";;;;;;;;;")).replace(";",""))
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,JARDIN DE ESTRELLAS,850 # 1250 # 1250,9.3,9.4,Baño privado # Zona de pícnic # Mobiliario ext...,4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990 # 1090 # 1190 # 850 # 990 # 1090 # 1190 # ...,7.7,8.0,Papel higiénico # Toallas # Bañera o ducha # W...,3
2,Bacalar,14,HOTEL CANTO,750 # 950,7.9,7.7,Papel higiénico # Toallas # Toallas / sábanas ...,3
4,Bacalar,21,Cabañas Colibrí,1138 # 1264 # 1277 # 1419 # 1457 # 1589 # 1637...,7.3,7.0,Abierta todo el año # Horario de apertura # Pa...,3
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,Papel higiénico # Toallas # Toallas / sábanas ...,0
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974 # 984 # 1036 # 963,4.7,4.3,Horno # Secadora de ropa # Cocina # Lavadora #...,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,Secadora de ropa # Cocina # Lavadora # Ropa de...,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,Abierta todo el año # Para todas las edades # ...,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,Abierta todo el año # Para todas las edades # ...,0
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,Mesa de comedor # Utensilios de cocina # Cocin...,4

In [11]:
PM = [
    'Compostela', 'Isla Aguada', 'Bacalar', 'Isla Mujeres', 
    'Sayulita', 'Todos Santos', 'Mazunte', 'Loreto', 
    'Tulum', 'Centro Tulum', 'Sisal', 'Papantla de Olarte'
]

In [12]:
booking = booking[booking.city.isin(PM)]
booking

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,JARDIN DE ESTRELLAS,850 # 1250 # 1250,9.3,9.4,Baño privado # Zona de pícnic # Mobiliario ext...,4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990 # 1090 # 1190 # 850 # 990 # 1090 # 1190 # ...,7.7,8.0,Papel higiénico # Toallas # Bañera o ducha # W...,3
2,Bacalar,14,HOTEL CANTO,750 # 950,7.9,7.7,Papel higiénico # Toallas # Toallas / sábanas ...,3
4,Bacalar,21,Cabañas Colibrí,1138 # 1264 # 1277 # 1419 # 1457 # 1589 # 1637...,7.3,7.0,Abierta todo el año # Horario de apertura # Pa...,3
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,Papel higiénico # Toallas # Toallas / sábanas ...,0
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974 # 984 # 1036 # 963,4.7,4.3,Horno # Secadora de ropa # Cocina # Lavadora #...,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,Secadora de ropa # Cocina # Lavadora # Ropa de...,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,Abierta todo el año # Para todas las edades # ...,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,Abierta todo el año # Para todas las edades # ...,0
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,Mesa de comedor # Utensilios de cocina # Cocin...,4

In [13]:
booking.city = booking.city.str.replace('Centro Tulum','Tulum')
booking

/home/jazmin/.local/lib/python3.8/site-packages/pandas/core/generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

,city,comments,name,prices,quality_price,rating,services,stars
0,Compostela,64,JARDIN DE ESTRELLAS,850 # 1250 # 1250,9.3,9.4,Baño privado # Zona de pícnic # Mobiliario ext...,4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990 # 1090 # 1190 # 850 # 990 # 1090 # 1190 # ...,7.7,8.0,Papel higiénico # Toallas # Bañera o ducha # W...,3
2,Bacalar,14,HOTEL CANTO,750 # 950,7.9,7.7,Papel higiénico # Toallas # Toallas / sábanas ...,3
4,Bacalar,21,Cabañas Colibrí,1138 # 1264 # 1277 # 1419 # 1457 # 1589 # 1637...,7.3,7.0,Abierta todo el año # Horario de apertura # Pa...,3
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,Papel higiénico # Toallas # Toallas / sábanas ...,0
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974 # 984 # 1036 # 963,4.7,4.3,Horno # Secadora de ropa # Cocina # Lavadora #...,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,Secadora de ropa # Cocina # Lavadora # Ropa de...,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,Abierta todo el año # Para todas las edades # ...,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,Abierta todo el año # Para todas las edades # ...,0
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,Mesa de comedor # Utensilios de cocina # Cocin...,4

In [14]:
booking.city.unique()

array(['Compostela', 'Isla Aguada', 'Bacalar', 'Isla Mujeres', 'Sayulita',
       'Todos Santos', 'Mazunte', 'Loreto', 'Tulum', 'Sisal',
       'Papantla de Olarte'], dtype=object)

In [28]:
booking.drop_duplicates(inplace=True)

<ipython-input-28-2b22e1efe0db>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  booking.drop_duplicates(inplace=True)

In [29]:
booking.to_csv('./data/booking_clean.csv',index=False)

In [30]:
bookingOHE = booking.drop("services",axis=1).join(booking.services.str.get_dummies(sep=" # "))
bookingOHE

,city,comments,name,prices,quality_price,rating,stars,Abierta todo el año,Acceso a pisos superiores en ascensor,Acceso a pisos superiores solo mediante escaleras,...,Zona de estar,Zona de fumadores,Zona de juegos interior,Zona de juegos para niños,Zona de pícnic,Zona de spa / relajación,Zona poco profunda,Zona privada de playa,Zona privada de playaDe pago,iPad
0,Compostela,64,JARDIN DE ESTRELLAS,850 # 1250 # 1250,9.3,9.4,4,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990 # 1090 # 1190 # 850 # 990 # 1090 # 1190 # ...,7.7,8.0,3,0,0,0,...,0,1,0,0,1,0,0,0,0,0
2,Bacalar,14,HOTEL CANTO,750 # 950,7.9,7.7,3,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Bacalar,21,Cabañas Colibrí,1138 # 1264 # 1277 # 1419 # 1457 # 1589 # 1637...,7.3,7.0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974 # 984 # 1036 # 963,4.7,4.3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
941,Tulum,3,BIT TULUM Villas,2671 # 2873,7.5,7.7,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
bookingOHE.prices = booking.prices.apply(lambda x: int(x.split("#")[0]))
bookingOHE

,city,comments,name,prices,quality_price,rating,stars,Abierta todo el año,Acceso a pisos superiores en ascensor,Acceso a pisos superiores solo mediante escaleras,...,Zona de estar,Zona de fumadores,Zona de juegos interior,Zona de juegos para niños,Zona de pícnic,Zona de spa / relajación,Zona poco profunda,Zona privada de playa,Zona privada de playaDe pago,iPad
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,0,0,0,...,0,1,0,0,1,0,0,0,0,0
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
bookingOHE.to_csv('./data/bookingSolPlaya_OHE.csv',index=False)

## Reducción de servicios en categorías:
+ **Heredados** Aquellos que provienen de recursos naturales
+ **Acceso y comunicación** Aquellos que permiten una comunicación al huésped, como el habla de idiomas extranjeros, wifi, teléfono, transporte, etc.
+ **Entretenimiento** Actividades extras dentro y fuera del hotel.
+ **Inclusión** Aquellos servicios que tienen en cuenta a personas algún tipo de discapacidad.
+ **Apto para infantes** Servicios que indican la inclusión de niños.
+ **Restaurante/Bar** Servicios en relación a la comida y bebidas.
+ **~Pet Friendly** Si las mascotas son permitidas o no dentro del hotel

In [33]:
booking_servicios = bookingOHE[bookingOHE.columns[:7]].copy()
booking_servicios

,city,comments,name,prices,quality_price,rating,stars
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0
...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4

In [34]:
list(bookingOHE.columns[7:])

['Abierta todo el año',
 'Acceso a pisos superiores en ascensor',
 'Acceso a pisos superiores solo mediante escaleras',
 'Acceso al salón executive',
 'Adaptado para sillas de ruedas',
 'Adaptado personas de movilidad reducida',
 'Adecuada para niños',
 'Adosado',
 'Aeróbic',
 'AeróbicDe pago',
 'AeróbicFuera del alojamientoDe pago',
 'Aire acondicionado',
 'Aire acondicionadoDe pago',
 'Alarma de seguridad',
 'Albornoz',
 'Alemán',
 'Almuerzos para llevar',
 'Alquiler de bicicletas (de pago)',
 'Alquiler de coches',
 'Apartamento privado en edificio',
 'Apoyo visual: braille',
 'Apoyo visual: carteles táctiles',
 'Armario',
 'Artículos de aseo gratis',
 'Ascensor',
 'Aseo adicional',
 'Aseo compartido',
 'Balcón',
 'Bar',
 'Bar en la piscina',
 'Bar(No disponible temporalmente)',
 'Barandillas de seguridad para bebés',
 'Barandillas protectoras para bebés',
 'Barbacoa',
 'BarbacoaDe pago',
 'Bañera',
 'Bañera de hidromasaje',
 'Bañera de hidromasaje / jacuzzi',
 'Bañera de hidromasaje / jacuzziDe pago',
 'Bañera o ducha',
 'Baño adicional',
 'Baño al aire libre',
 'Baño al aire libreDe pago',
 'Baño compartido',
 'Baño de vapor',
 'Baño privado',
 'Baño público',
 'Baño públicoDe pago',
 'Baños termales',
 'Bicicletas disponibles (gratis)',
 'Bidet',
 'Billar',
 'BillarDe pago',
 'Bingo',
 'Boles para mascotas',
 'Buffet para niños',
 'Cafetería en el alojamiento',
 'Caja fuerte',
 'Caja fuerte para ordenador portátil',
 'Caja fuerteDe pago',
 'Cajero automático en el hotel',
 'Calefacción',
 'Cama plegable',
 'Camas extralargas (más de 2 metros)',
 'Cambio de moneda',
 'Campo de golf (a menos de 3 km)De pago',
 'Canales de pago',
 'Canales por cable',
 'Canales vía satélite',
 'Canguro / servicios para niños',
 'Canguro / servicios para niñosDe pago',
 'Capilla',
 'Catalán',
 'Cenas temáticas',
 'Cenas temáticasDe pago',
 'Cenas temáticasFuera del alojamiento',
 'Cenas temáticasFuera del alojamientoDe pago',
 'Centro de negocios',
 'Centro de negociosDe pago',
 'Cesta para mascotas',
 'Chimenea exterior',
 'Ciclismo',
 'CiclismoFuera del alojamiento',
 'Clases de cocina',
 'Clases de cocinaDe pago',
 'Clases de cocinaFuera del alojamiento',
 'Clases de cocinaFuera del alojamientoDe pago',
 'Clases de fitness',
 'Clases de yoga',
 'Club infantil',
 'Cochecitos de bebé',
 'Cocina',
 'Cocina compartida',
 'Comedia en vivoDe pago',
 'Corte de pelo',
 'Cubierta para piscina',
 'Cámaras de seguridad en las zonas comunitarias',
 'Cámaras de seguridad fuera del alojamiento',
 'Dardos',
 'De temporada',
 'Desayuno en la habitación',
 'Detector de monóxido de carbono',
 'Detectores de humo',
 'Discoteca / DJ',
 'Discoteca / DJDe pago',
 'Ducha',
 'Enchufe cerca de la cama',
 'Entrada privada',
 'Entrenador personal',
 'Entretenimiento nocturno',
 'Entretenimiento nocturnoDe pago',
 'Envoltura corporal',
 'Equipamiento de bádminton',
 'Equipamiento de juegos para exterior',
 'Equipamiento de tenis',
 'Equipamiento de tenisDe pago',
 'Equipo de planchado',
 'Equitación',
 'EquitaciónDe pago',
 'EquitaciónFuera del alojamiento',
 'EquitaciónFuera del alojamientoDe pago',
 'Escritorio',
 'Español',
 'EsquíFuera del alojamiento',
 'Estación de carga de vehículos eléctricos',
 'Eventos deportivos en directo (emisión)',
 'Eventos deportivos en directo (emisión)De pago',
 'Eventos deportivos en directo (emisión)Fuera del alojamiento',
 'Eventos deportivos en directo (emisión)Fuera del alojamientoDe pago',
 'Exfoliación corporal',
 'Extintores',
 'Fax / fotocopiadora',
 'Fax / fotocopiadoraDe pago',
 'Fogones',
 'Francés',
 'Fruta',
 'FrutaDe pago',
 'Galerías de arte temporales',
 'Galerías de arte temporalesDe pago',
 'Galerías de arte temporalesFuera del alojamiento',
 'Galerías de arte temporalesFuera del alojamientoDe pago',
 'Gimnasio',
 'GimnasioDe pago',
 'Guardaequipaje',
 'GuardaequipajeDe pago',
 'Guyaratí',
 'Habitaciones comunicadas disponibles',
 'Habitaciones familiares',
 'Habitaciones hipoalergénicas',
 'Habitaciones insonorizadas',
 'Habitaciones sin humo',
 'Hammam',
 'Happy hour',
 'Happy hourDe pago',
 'Hebreo',
 'Hervidor eléctrico',
 'Hindi',
 'Hipoalergénico',
 'Holandés',
 'Horario de apertura',
 'Horno',
 'Húngaro',
 'Independiente',
 'Información turística',
 'Inglés',
 'Insonorización',
 'Instalaciones de spa',
 'Instalaciones para deportes acuáticos en el alojamiento',
 'Instalaciones para deportes acuáticos en el alojamientoDe pago',
 'Italiano',
 'Japonés',
 'Jardín',
 'Juegos de mesa / puzles',
 'Juguetes para la piscina',
 'Karaoke',
 'Lavadora',
 'Lavamanos más bajo',
 'Lavavajillas',
 'Libros DVD o música para niños',
 'Llave de acceso',
 'Manicura',
 'Masaje corporal completo',
 'Masaje corporal completoDe pago',
 'Masaje de cabeza',
 'Masaje de cabezaDe pago',
 'Masaje de cuello',
 'Masaje de cuelloDe pago',
 'Masaje de espalda',
 'Masaje de espaldaDe pago',
 'Masaje de manos',
 'Masaje de manosDe pago',
 'Masaje de pies',
 'Masaje de piesDe pago',
 'Masaje en pareja',
 'Masaje en parejaDe pago',
 'Masajes',
 'MasajesDe pago',
 'Menú para niños',
 'Menú para niñosDe pago',
 'Menús para dietas especiales (bajo petición)',
 'Mesa de comedor',
 'Microondas',
 'Minibar',
 'Minigolf',
 'MinigolfDe pago',
 'Mobiliario exterior',
 'Mosquitera',
 'Muebles de exterior',
 'Máquina expendedora (aperitivos)',
 'Máquina expendedora (bebidas)',
 'Música / espectáculos en directo',
 'Música / espectáculos en directoDe pago',
 'Música / espectáculos en directoFuera del alojamiento',
 'Música / espectáculos en directoFuera del alojamientoDe pago',
 'Nevera',
 'Noches de cine',
 'Noches de cineFuera del alojamiento',
 'Noches de cineFuera del alojamientoDe pago',
 'Ordenador',
 'Ordenador portátil',
 'Papel higiénico',
 'Paquetes de spa / bienestar',
 'Para todas las edades',
 'Parking adaptado para personas de movilidad reducida',
 'Parking en la calle',
 'Parking en un garaje',
 'Parking vigilado',
 'Parque acuático',
 'Parque acuáticoDe pago',
 'Parque acuáticoFuera del alojamiento',
 'Parque acuáticoFuera del alojamientoDe pago',
 'Patio',
 'Pedicura',
 'Pediluvio',
 'Peinado',
 'Peluquería / salón de belleza',
 'Perchero',
 'Personal de animación',
 'Pesca',
 'PescaDe pago',
 'PescaFuera del alojamiento',
 'PescaFuera del alojamientoDe pago',
 'Ping pong',
 'Piragüismo',
 'PiragüismoDe pago',
 'PiragüismoFuera del alojamiento',
 'PiragüismoFuera del alojamientoDe pago',
 'Piscina climatizada',
 'Piscina con vistas',
 'Piscina de agua salada',
 'Piscina en la azotea',
 'Piscina infantil',
 'Piscina infinita',
 'Piscina pequeña',
 'Piscina privada',
 'Pista de tenisFuera del alojamiento',
 'Plancha para pantalones',
 'Plancha para pantalonesDe pago',
 'Plancha para ropa',
 'Playa',
 'Polaco',
 'Portugués',
 'Productos de limpieza',
 'Prohibido fumar en todo el alojamiento',
 'Proporciona factura',
 'Protector de enchufes para niños',
 'Radio',
 'Recepción 24 horas',
 'Registro de entrada / salida privado',
 'Registro de entrada y salida exprés',
 'Registro de entrada y salida exprésDe pago',
 'Reloj despertador',
 'Reproductor de CD',
 'Reproductor de DVD',
 'Restaurante',
 'Restaurante(No disponible temporalmente)',
 'Ropa de cama',
 'Rumano',
 'Ruso',
 'Ruta de bares',
 'Ruta de baresDe pago',
 'Sala de juegos',
 'Salas de reuniones / banquetes',
 'Salas de reuniones / banquetesDe pago',
 'Sauna',
 'SaunaDe pago',
 'Secador de pelo',
 'Secadora de ropa',
 'Seguridad 24 horas',
 'Senderismo',
 'SenderismoDe pago',
 'SenderismoFuera del alojamiento',
 'SenderismoFuera del alojamientoDe pago',
 'Servicio de conserjería',
 'Servicio de despertador',
 'Servicio de despertador / alarma',
 'Servicio de entrega de comestibles',
 'Servicio de entrega de comestiblesDe pago',
 'Servicio de habitaciones',
 'Servicio de lavandería',
 'Servicio de lavanderíaDe pago',
 'Servicio de limpieza diario',
 'Servicio de limpieza diarioDe pago',
 'Servicio de limpieza en seco',
 'Servicio de limpieza en secoDe pago',
 'Servicio de planchado',
 'Servicio de planchadoDe pago',
 'Servicio de recogida en el aeropuerto',
 'Servicio de recogida en el aeropuertoDe pago',
 'Servicio de traslado',
 'Servicio de traslado (de pago)',
 'Servicio de traslado al aeropuerto',
 'Servicio de traslado al aeropuertoDe pago',
 'Servicios de belleza',
 'Servicios de depilación',
 'Servicios de maquillaje',
 'Silla de masajes',
 'Situado frente a la playa',
 'Snack-bar',
 'Snorkel',
 'SnorkelDe pago',
 'SnorkelFuera del alojamiento',
 'SnorkelFuera del alojamientoDe pago',
 'Sofá',
 'Sofá cama',
 'Solo para adultos',
 'Solárium',
 'SoláriumDe pago',
 'Sombrillas',
 'SombrillasDe pago',
 'Soporte para iPod',
 'Spa y centro de bienestar',
 'Spa y centro de bienestar(No disponible temporalmente)De pago',
 'Spa y centro de bienestarDe pago',
 'Submarinismo',
 'SubmarinismoDe pago',
 'SubmarinismoFuera del alojamiento',
 'SubmarinismoFuera del alojamientoDe pago',
 'Suelo de baldosa / mármol',
 'Suelo de madera o parquet',
 'Suelo de moqueta',
 'Supermercado pequeño en el alojamiento',
 'TV',
 'TV de pantalla plana',
 'Taquillas',
 'Taquillas en el gimnasio / spa',
 'Tarjeta de acceso',
 'Tarjetas de transporte público',
 'Tarjetas de transporte públicoDe pago',
 'Teléfono',
 'Tendedero',
 'Terapia con luz',
 'Terraza',
 'Terraza / solárium',
 'Tetera / cafetera',
 'Tinte',
 'Toallas',
 'Toallas / sábanas (por un suplemento)',
 'Toallas de playa/piscina',
 'Tobogán de agua',
 'Toda la unidad accesible en silla de ruedas',
 'Toda la unidad en la planta baja',
 'Tostadora',
 'Tour o clase sobre cultura local',
 'Tour o clase sobre cultura localDe pago',
 'Tours a pie',
 'Tours a pieDe pago',
 'Tours en bici',
 'Tours en biciDe pago',
 'Traslado aeropuerto',
 'Traslado aeropuerto (de pago)',
 'Traslado aeropuerto (gratis)',
 'Tratamientos capilares',
 'Tratamientos corporales',
 'Tratamientos faciales',
 'Trona',
 'Tumbonas/sillas de playa',
 'Tumbonas/sillas de playaDe pago',
 'Utensilios de cocina',
 'Valla alrededor de la piscina',
 'Ventilador',
 'Vestidor',
 'Videoconsola Nintendo Wii',
 'Videoconsola PS2',
 'Videoconsola PS3',
 'Vino / champán',
 'Vino / champánDe pago',
 'Vistas',
 'Vistas a la montaña',
 'Vistas a la piscina',
 'Vistas a un lugar de interés',
 'Vistas a un patio interior',
 'Vistas al jardín',
 'Vistas al lago',
 'Vistas al mar',
 'Vídeo',
 'WC',
 'WC con barras de apoyo',
 'WC elevado',
 'WiFi',
 'WiFi de pago',
 'Windsurf',
 'WindsurfDe pago',
 'WindsurfFuera del alojamiento',
 'WindsurfFuera del alojamientoDe pago',
 'Zapatillas',
 'Zona TV / salón de uso compartido',
 'Zona de cocina',
 'Zona de comedor',
 'Zona de comedor exterior',
 'Zona de estar',
 'Zona de fumadores',
 'Zona de juegos interior',
 'Zona de juegos para niños',
 'Zona de pícnic',
 'Zona de spa / relajación',
 'Zona poco profunda',
 'Zona privada de playa',
 'Zona privada de playaDe pago',
 'iPad']

### Servicios heredados

In [35]:
heredados = [
'Baños termales',
'Pesca', 'PescaDe pago', 
'Playa', 'Vistas',
 'Vistas a la montaña', 'Vistas al lago', 'Vistas al mar', 
 'Situado frente a la playa', 
 ]

In [36]:
booking_servicios['heredados'] = bookingOHE[heredados].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1
...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0

In [37]:
booking_servicios['total_heredados'] =  bookingOHE[heredados].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3
...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0

### Acceso y comunicación

In [38]:
acceso =[
'Alemán','Alquiler de bicicletas (de pago)', 'Alquiler de coches',
'Bicicletas disponibles (gratis)', 'Catalán', 'Fax / fotocopiadora',
'Fax / fotocopiadoraDe pago', 'Francés', 'Guyaratí', 'Hebreo', 
'Hindi', 'Húngaro', 'Inglés','Italiano', 'Japonés', 'Ordenador', 
'Ordenador portátil','Polaco', 'Portugués', 'Radio', 
'Recepción 24 horas', 'Rumano', 'Ruso', 'Servicio de recogida en el aeropuerto',
'Servicio de recogida en el aeropuertoDe pago', 'Servicio de traslado', 
'Servicio de traslado (de pago)',
'Servicio de traslado al aeropuerto','Servicio de traslado al aeropuertoDe pago',
'Tarjetas de transporte público', 'Tarjetas de transporte públicoDe pago',
'Teléfono', 'Traslado aeropuerto', 'Traslado aeropuerto (de pago)',
'Traslado aeropuerto (gratis)', 'WiFi', 'WiFi de pago', 
]

In [39]:
booking_servicios['acceso/comunicacion'] =  bookingOHE[acceso].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1
...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1

In [40]:
booking_servicios['total_acceso/comunicacion'] =  bookingOHE[acceso].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2

### Entretenimiento y deporte

In [41]:
entretenimiento = [
'Aeróbic', 'AeróbicDe pago', 'AeróbicFuera del alojamientoDe pago',
'Canales por cable', 'Canales vía satélite', 'Ciclismo',
'CiclismoFuera del alojamiento', 'Clases de cocina', 'Clases de cocinaDe pago',
'Clases de cocinaFuera del alojamiento', 'Clases de cocinaFuera del alojamientoDe pago',
'Clases de fitness', 'Clases de yoga', 'Comedia en vivoDe pago', 'Discoteca / DJ', 'Discoteca / DJDe pago', 'Entrada privada',
 'Entrenador personal', 'Entretenimiento nocturno', 'Entretenimiento nocturnoDe pago',
'Equipamiento de bádminton', 'Equipamiento de juegos para exterior',
'Equipamiento de tenis', 'Equipamiento de tenisDe pago', 'Equitación',
'EquitaciónDe pago', 'EquitaciónFuera del alojamiento', 'EquitaciónFuera del alojamientoDe pago',
'EsquíFuera del alojamiento','Eventos deportivos en directo (emisión)', 'Eventos deportivos en directo (emisión)De pago', 'Eventos deportivos en directo (emisión)Fuera del alojamiento',
'Eventos deportivos en directo (emisión)Fuera del alojamientoDe pago',
'FrutaDe pago', 'Galerías de arte temporales', 'Galerías de arte temporalesDe pago',
'Galerías de arte temporalesFuera del alojamiento', 'Galerías de arte temporalesFuera del alojamientoDe pago',
'Gimnasio', 'GimnasioDe pago', 'Happy hour', 'Happy hourDe pago',
'Instalaciones para deportes acuáticos en el alojamiento',
'Instalaciones para deportes acuáticos en el alojamientoDe pago',
'Juguetes para la piscina', 'Karaoke', 'Minibar', 'Minigolf', 'MinigolfDe pago',
'Música / espectáculos en directo', 'Música / espectáculos en directoDe pago', 'Música / espectáculos en directoFuera del alojamiento',
'Música / espectáculos en directoFuera del alojamientoDe pago',
'Noches de cine', 'Noches de cineFuera del alojamiento', 'Noches de cineFuera del alojamientoDe pago', 'Parque acuático', 'Parque acuáticoDe pago', 'Parque acuáticoFuera del alojamiento', 'Parque acuáticoFuera del alojamientoDe pago',
'Personal de animación', 'Ping pong', 'Piragüismo',
 'PiragüismoDe pago', 'PiragüismoFuera del alojamiento',
 'PiragüismoFuera del alojamientoDe pago', 'Piscina climatizada',
 'Piscina con vistas', 'Piscina de agua salada', 'Piscina en la azotea',
'Piscina infinita', 'Piscina pequeña', 'Piscina privada',
'Pista de tenisFuera del alojamiento', 'Reproductor de CD',
'Reproductor de DVD', 'Sala de juegos', 'Seguridad 24 horas',
'Senderismo', 'SenderismoDe pago', 'SenderismoFuera del alojamiento',
'SenderismoFuera del alojamientoDe pago', 'Snorkel', 'SnorkelDe pago',
'SnorkelFuera del alojamiento', 'SnorkelFuera del alojamientoDe pago',
'Spa y centro de bienestarDe pago', 'Submarinismo', 'SubmarinismoDe pago',
'SubmarinismoFuera del alojamiento', 'SubmarinismoFuera del alojamientoDe pago', 
'TV', 'TV de pantalla plana',
'Tour o clase sobre cultura local', 'Tour o clase sobre cultura localDe pago',
'Tours a pie', 'Tours a pieDe pago', 'Tours en bici', 'Tours en biciDe pago',
'Windsurf', 'WindsurfDe pago', 'WindsurfFuera del alojamiento',
'WindsurfFuera del alojamientoDe pago',
]

In [42]:
booking_servicios['entretenimiento/deporte'] =  bookingOHE[entretenimiento].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1

In [43]:
booking_servicios['total_entretenimiento/deporte'] =  bookingOHE[entretenimiento].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4

### Inclusión

In [44]:
inclusion = [
'Acceso a pisos superiores en ascensor', 'Adaptado para sillas de ruedas',
'Ascensor','Adaptado personas de movilidad reducida',
'Apoyo visual: braille', 'Apoyo visual: carteles táctiles',  'Parking adaptado para personas de movilidad reducida', 'WC con barras de apoyo',
'WC elevado',
]

In [45]:
booking_servicios['inclusion'] = bookingOHE[inclusion].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0

In [46]:
booking_servicios['total_inclusion'] =  bookingOHE[inclusion].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0,0
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0,0
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0,0
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0

### Apto para niños

In [47]:
ninios = [
'Adecuada para niños', 'Barandillas de seguridad para bebés',
'Barandillas protectoras para bebés', 'Buffet para niños',
'Canguro / servicios para niños','Canguro / servicios para niñosDe pago',
'Club infantil','Cochecitos de bebé', 'Habitaciones familiares',
'Libros DVD o música para niños', 'Menú para niños', 
'Menú para niñosDe pago', 'Protector de enchufes para niños', 
'Para todas las edades', 'Piscina infantil','Zona de juegos para niños',
]

In [48]:
booking_servicios['ninios'] =  bookingOHE[ninios].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0,0,1
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1,1,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0,0,1
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0,0,1
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0,0,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0,0,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0,1

In [49]:
booking_servicios['total_ninios'] =  bookingOHE[ninios].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0,0,1,3
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1,1,1,2
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0,0,1,2
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0,0,1,2
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0,0,0,0
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0,0,0,0
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0,0,1,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0,0,1,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0,1,1

### Comida

In [50]:
comida = [
'Almuerzos para llevar', 'Bar', 'Bar en la piscina',
'Bar(No disponible temporalmente)', 'Barbacoa',
'BarbacoaDe pago', 'Cafetería en el alojamiento',
'Catalán', 'Cenas temáticas', 'Cenas temáticasDe pago',
'Cenas temáticasFuera del alojamiento', 'Cenas temáticasFuera del alojamientoDe pago',
'Cocina', 'Cocina compartida', 'Desayuno en la habitación',
'Fruta', 'FrutaDe pago', 'Horno','Menús para dietas especiales (bajo petición)',
'Microondas', 'Minibar', 'Máquina expendedora (aperitivos)',
'Máquina expendedora (bebidas)',  'Zona de pícnic',
]

In [51]:
booking_servicios['comida/bebida'] =  bookingOHE[comida].any(axis=1).astype('int16')
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0,0,1,3,1
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1,1,1,2,1
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0,0,1,2,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0,0,1,2,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0,0,0,0,1
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0,0,0,0,1
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0,0,1,1,1
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0,0,1,1,1
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0,1,1,1

In [52]:
booking_servicios['total_comida/bebida'] =  bookingOHE[comida].sum(axis=1)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida,total_comida/bebida
0,Compostela,64,JARDIN DE ESTRELLAS,850,9.3,9.4,4,0,0,1,2,1,9,0,0,1,3,1,4
1,Isla Aguada,235,"Freedom Shores ""La Gringa"" Hotel - Universally...",990,7.7,8.0,3,1,2,1,3,1,2,1,1,1,2,1,6
2,Bacalar,14,HOTEL CANTO,750,7.9,7.7,3,0,0,1,1,1,5,0,0,1,2,0,0
4,Bacalar,21,Cabañas Colibrí,1138,7.3,7.0,3,0,0,1,1,1,1,0,0,1,2,0,0
6,Bacalar,15,Casa baklahar frente a Laguna,916,6.8,6.5,0,1,3,1,1,1,1,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Tulum,9,Jungla 22 aldea tulum,974,4.7,4.3,0,0,0,1,1,1,3,0,0,0,0,1,2
931,Tulum,3,☆Amazing PH Suk Ha☆ La Veleta,3138,9.2,9.3,0,0,0,1,1,1,3,0,0,0,0,1,1
932,Tulum,6,Cien Corazones,7172,9.2,9.8,0,0,0,1,1,1,5,0,0,1,1,1,4
939,Tulum,4,Taanah Poolview 1BR apartment Ecochic,1694,8.8,9.0,0,0,0,1,1,1,4,0,0,1,1,1,2
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0,1,1,1,2

In [53]:
booking_servicios.sort_values(by="city",inplace=True)
booking_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida,total_comida/bebida
145,Bacalar,1.320,Hotel CasaBakal - A pie de Laguna - Bacalar,3871,7.7,8.5,5,1,2,1,3,1,11,0,0,1,1,1,5
120,Bacalar,206,Vias Maya Bacalar Hotel,500,8.4,7.9,0,0,0,0,0,0,0,0,0,0,0,0,0
118,Bacalar,551,Yaxche Centro Hostal y Camping,414,8.1,7.8,0,0,0,1,2,1,8,0,0,0,0,1,3
117,Bacalar,295,Hotel Casa Ariana,720,8.6,8.4,2,0,0,1,1,1,4,0,0,0,0,0,0
115,Bacalar,419,Xibalba in town,1200,8.5,8.2,0,0,0,1,2,1,1,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,Tulum,131,Tago Tulum by G Hotels,15784,7.9,8.7,5,1,2,1,7,1,4,0,0,1,1,1,4
492,Tulum,277,Chavez Eco Beach Camping and Cabañas,1050,8.6,8.9,0,1,2,1,2,1,2,1,4,1,1,1,2
491,Tulum,21,Casa Leo,1101,8.5,8.0,3,0,0,1,1,1,3,1,2,1,2,1,2
501,Tulum,170,Sueños Tulum,8547,8.3,9.3,4,1,2,1,5,1,3,1,1,1,3,1,4
941,Tulum,3,BIT TULUM Villas,2671,7.5,7.7,4,0,0,1,2,1,4,0,0,1,1,1,2

In [54]:
booking_servicios.describe()

,prices,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,inclusion,total_inclusion,ninios,total_ninios,comida/bebida,total_comida/bebida
count,615.000000,615.000000,615.000000,615.00000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000,615.000000
mean,2407.894309,8.298699,2.190244,0.35935,0.652033,0.936585,3.492683,0.925203,5.495935,0.229268,0.398374,0.669919,1.108943,0.795122,2.378862
std,3101.529576,0.929939,1.803336,0.48020,0.993083,0.243906,2.522768,0.263277,4.555438,0.420704,0.907262,0.470625,1.047489,0.403941,2.155489
min,159.000000,1.300000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,985.000000,7.900000,0.000000,0.00000,0.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,1560.000000,8.400000,3.000000,0.00000,0.000000,1.000000,3.000000,1.000000,4.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000
75%,2610.500000,8.900000,4.000000,1.00000,1.000000,1.000000,6.000000,1.000000,8.000000,0.000000,0.000000,1.000000,2.000000,1.000000,4.000000
max,51797.000000,10.000000,5.000000,1.00000,4.000000,1.000000,11.000000,1.000000,34.000000,1.000000,6.000000,1.000000,7.000000,1.000000,13.000000

In [55]:
booking_servicios.to_csv('./data/booking_servicios_sumas_clasificados.csv',index=False)

# Trip Advisor

In [56]:
trip = pd.read_csv('./tripadvisor/tripadvisorSolPlaya.csv')
trip

,city,comments,name,prices,quality_price,rating,services,stars,url
0,Isla Mujeres,100 opiniones,"Icaco Island Village Apartamento, Isla Mujeres",NaN,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1,Riviera Nayarit,3 opiniones,"Ximena Hotel Boutique, Sayulita, Nayarit",NaN,NaN,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g4...
2,Isla Mujeres,7 opiniones,Ocean Drive Hotel - Isla Mujeres,NaN,NaN,2.5,"Estacionamiento público gratuito cercano,Wifi,...",3.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
3,Isla Mujeres,3 opiniones,"Hotel Maria Elena, Isla Mujeres",NaN,NaN,4.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
4,Isla Mujeres,105 opiniones,"Chichi's 'n Charlies Rancho, Isla Mujeres",NaN,ui_bubble_rating bubble_40,3.5,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
...,...,...,...,...,...,...,...,...,...
1497,Todos Santos,9 opiniones,"Osprey San Pedrito Villa vacacional, Todos San...",NaN,ui_bubble_rating bubble_50,5.0,Playa,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1498,Todos Santos,295 opiniones,"Arriba de la Roca, Todos Santos, Baja California",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1499,Todos Santos,26 opiniones,"CalyCanto Casitas Villa vacacional, Todos Sant...",NaN,ui_bubble_rating bubble_50,5.0,"Estacionamiento gratis,Internet de alta veloci...",NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1500,Todos Santos,46 opiniones,"Flora del Mar Posada, Todos Santos, Baja Calif...",NaN,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas,https://www.tripadvisor.com.mx/Hotel_Review-g1...
1501,Todos Santos,NaN,"Jardin de Pilar Rancho, Todos Santos, Baja Cal...",NaN,NaN,NaN,NaN,NaN,https://www.tripadvisor.com.mx/Hotel_Review-g1...

In [57]:
trip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1502 entries, 0 to 1501
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           1502 non-null   object
 1   comments       1123 non-null   object
 2   name           1502 non-null   object
 3   prices         182 non-null    object
 4   quality_price  734 non-null    object
 5   rating         1123 non-null   float64
 6   services       994 non-null    object
 7   stars          411 non-null    object
 8   url            1502 non-null   object
dtypes: float64(1), object(8)
memory usage: 105.7+ KB

In [58]:
trip.dropna(subset=["prices"],inplace=True)
trip.drop("url",axis=1,inplace=True)

## Comments

In [59]:
trip.comments = trip.comments.apply(lambda x: int(str(x.split()[0]).replace(",","")) if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,"Mar y Suenos B & B, Sayulita, Nayarit","$1,553,$1,553,$1,574",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN
14,Riviera Nayarit,14,"Paraíso Sayulita Alojamiento, Nayarit","$2,140",ui_bubble_rating bubble_50,5.0,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,"$7,111,$7,111",ui_bubble_rating bubble_50,5.0,"Estacionamiento público gratuito cercano,Inter...",NaN
21,Riviera Maya,602,"Casa Malca Hotel, Tulum","$19,189,$16,165,$16,165",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,"$3,993,$3,595,$3,993,$3,619,$3,595",ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
...,...,...,...,...,...,...,...,...
1490,Tepic,19,"Hotel Villa Las Rosas, Tepic, Nayarit","$695,$695,$695",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1491,Tepic,33,"Hotel Ejecutivo Tepic, Nayarit","$828,$828,$642,$828,$828",ui_bubble_rating bubble_35,3.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1492,Tepic,23,"Hotel Tepic, Nayarit","$890,$890,$890",ui_bubble_rating bubble_40,3.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas
1493,Tepic,483,"Fiesta Inn Tepic Hotel, Nayarit","$1,304,$1,305",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas
1495,Tepic,247,"NK Hotel Nekié Tepic, Nayarit","$1,035,$1,155,$1,098",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",3.5 de 5 burbujas

## Name

In [60]:
trip.name = trip.name.apply(lambda x: x.split(",")[0])
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,Mar y Suenos B & B,"$1,553,$1,553,$1,574",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN
14,Riviera Nayarit,14,Paraíso Sayulita Alojamiento,"$2,140",ui_bubble_rating bubble_50,5.0,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,"$7,111,$7,111",ui_bubble_rating bubble_50,5.0,"Estacionamiento público gratuito cercano,Inter...",NaN
21,Riviera Maya,602,Casa Malca Hotel,"$19,189,$16,165,$16,165",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,"$3,993,$3,595,$3,993,$3,619,$3,595",ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
...,...,...,...,...,...,...,...,...
1490,Tepic,19,Hotel Villa Las Rosas,"$695,$695,$695",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1491,Tepic,33,Hotel Ejecutivo Tepic,"$828,$828,$642,$828,$828",ui_bubble_rating bubble_35,3.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1492,Tepic,23,Hotel Tepic,"$890,$890,$890",ui_bubble_rating bubble_40,3.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas
1493,Tepic,483,Fiesta Inn Tepic Hotel,"$1,304,$1,305",ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas
1495,Tepic,247,NK Hotel Nekié Tepic,"$1,035,$1,155,$1,098",ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",3.5 de 5 burbujas

## Prices

In [61]:
trip.prices = trip.prices.apply(lambda x: x.replace(",$"," # ").replace("$","").replace(",","") if str(x)!="nan" else np.nan)
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,Mar y Suenos B & B,1553 # 1553 # 1574,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN
14,Riviera Nayarit,14,Paraíso Sayulita Alojamiento,2140,ui_bubble_rating bubble_50,5.0,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,7111 # 7111,ui_bubble_rating bubble_50,5.0,"Estacionamiento público gratuito cercano,Inter...",NaN
21,Riviera Maya,602,Casa Malca Hotel,19189 # 16165 # 16165,ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,3993 # 3595 # 3993 # 3619 # 3595,ui_bubble_rating bubble_40,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
...,...,...,...,...,...,...,...,...
1490,Tepic,19,Hotel Villa Las Rosas,695 # 695 # 695,ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1491,Tepic,33,Hotel Ejecutivo Tepic,828 # 828 # 642 # 828 # 828,ui_bubble_rating bubble_35,3.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1492,Tepic,23,Hotel Tepic,890 # 890 # 890,ui_bubble_rating bubble_40,3.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas
1493,Tepic,483,Fiesta Inn Tepic Hotel,1304 # 1305,ui_bubble_rating bubble_45,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas
1495,Tepic,247,NK Hotel Nekié Tepic,1035 # 1155 # 1098,ui_bubble_rating bubble_40,4.0,"Estacionamiento gratis,Internet de alta veloci...",3.5 de 5 burbujas

## Quality price

In [62]:
trip.quality_price = trip.quality_price.apply(lambda x: int(x.split("_")[-1])/10 if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,Mar y Suenos B & B,1553 # 1553 # 1574,4.5,4.5,"Estacionamiento gratis,Internet de alta veloci...",NaN
14,Riviera Nayarit,14,Paraíso Sayulita Alojamiento,2140,5.0,5.0,"Internet de alta velocidad gratuito (WiFi),Wif...",NaN
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,7111 # 7111,5.0,5.0,"Estacionamiento público gratuito cercano,Inter...",NaN
21,Riviera Maya,602,Casa Malca Hotel,19189 # 16165 # 16165,4.0,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,3993 # 3595 # 3993 # 3619 # 3595,4.0,4.5,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
...,...,...,...,...,...,...,...,...
1490,Tepic,19,Hotel Villa Las Rosas,695 # 695 # 695,4.0,4.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1491,Tepic,33,Hotel Ejecutivo Tepic,828 # 828 # 642 # 828 # 828,3.5,3.0,"Estacionamiento gratis,Internet de alta veloci...",4.0 de 5 burbujas
1492,Tepic,23,Hotel Tepic,890 # 890 # 890,4.0,3.5,"Estacionamiento gratis,Internet de alta veloci...",2.0 de 5 burbujas
1493,Tepic,483,Fiesta Inn Tepic Hotel,1304 # 1305,4.5,4.5,"Estacionamiento gratis,Internet de alta veloci...",3.0 de 5 burbujas
1495,Tepic,247,NK Hotel Nekié Tepic,1035 # 1155 # 1098,4.0,4.0,"Estacionamiento gratis,Internet de alta veloci...",3.5 de 5 burbujas

## Services

In [63]:
trip.services = trip.services.apply(lambda x: x.replace(","," # ") if str(x)!="nan" else "")
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,Mar y Suenos B & B,1553 # 1553 # 1574,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,NaN
14,Riviera Nayarit,14,Paraíso Sayulita Alojamiento,2140,5.0,5.0,Internet de alta velocidad gratuito (WiFi) # W...,NaN
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,7111 # 7111,5.0,5.0,Estacionamiento público gratuito cercano # Int...,NaN
21,Riviera Maya,602,Casa Malca Hotel,19189 # 16165 # 16165,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,4.0 de 5 burbujas
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,3993 # 3595 # 3993 # 3619 # 3595,4.0,4.5,Estacionamiento gratis # Internet de alta velo...,4.0 de 5 burbujas
...,...,...,...,...,...,...,...,...
1490,Tepic,19,Hotel Villa Las Rosas,695 # 695 # 695,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,4.0 de 5 burbujas
1491,Tepic,33,Hotel Ejecutivo Tepic,828 # 828 # 642 # 828 # 828,3.5,3.0,Estacionamiento gratis # Internet de alta velo...,4.0 de 5 burbujas
1492,Tepic,23,Hotel Tepic,890 # 890 # 890,4.0,3.5,Estacionamiento gratis # Internet de alta velo...,2.0 de 5 burbujas
1493,Tepic,483,Fiesta Inn Tepic Hotel,1304 # 1305,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,3.0 de 5 burbujas
1495,Tepic,247,NK Hotel Nekié Tepic,1035 # 1155 # 1098,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,3.5 de 5 burbujas

## Stars

In [64]:
trip.stars = trip.stars.apply(lambda x: x.split()[0] if str(x)!="nan" else 0)
trip

,city,comments,name,prices,quality_price,rating,services,stars
13,Riviera Nayarit,33,Mar y Suenos B & B,1553 # 1553 # 1574,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,0
14,Riviera Nayarit,14,Paraíso Sayulita Alojamiento,2140,5.0,5.0,Internet de alta velocidad gratuito (WiFi) # W...,0
16,Riviera Maya,22,Layla Tulum - Boutique Hotel,7111 # 7111,5.0,5.0,Estacionamiento público gratuito cercano # Int...,0
21,Riviera Maya,602,Casa Malca Hotel,19189 # 16165 # 16165,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,4.0
24,Riviera Maya,493,Mereva Tulum by Blue sky Hotel,3993 # 3595 # 3993 # 3619 # 3595,4.0,4.5,Estacionamiento gratis # Internet de alta velo...,4.0
...,...,...,...,...,...,...,...,...
1490,Tepic,19,Hotel Villa Las Rosas,695 # 695 # 695,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,4.0
1491,Tepic,33,Hotel Ejecutivo Tepic,828 # 828 # 642 # 828 # 828,3.5,3.0,Estacionamiento gratis # Internet de alta velo...,4.0
1492,Tepic,23,Hotel Tepic,890 # 890 # 890,4.0,3.5,Estacionamiento gratis # Internet de alta velo...,2.0
1493,Tepic,483,Fiesta Inn Tepic Hotel,1304 # 1305,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,3.0
1495,Tepic,247,NK Hotel Nekié Tepic,1035 # 1155 # 1098,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,3.5

In [66]:
trip = trip[trip.city.isin(PM)]
trip

,city,comments,name,prices,quality_price,rating,services,stars
679,Bacalar,113,Villas Bakalar Hotel,2045 # 1840 # 1927,4.0,4.0,Estacionamiento gratis # Internet de alta velo...,5.0
694,Bacalar,197,Hostal & Suites Pata de Perro,562 # 656 # 656 # 656 # 627,4.5,4.5,Estacionamiento público gratuito cercano # Int...,0
696,Bacalar,128,Hotel Hacienda Bacalar,950 # 950 # 950,4.0,3.5,Estacionamiento gratis # Internet de alta velo...,3.0
698,Bacalar,55,Azul 36 Hotel,1744 # 1744 # 1744 # 1492 # 1492,2.0,4.0,Estacionamiento gratis # Internet de alta velo...,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250 # 2250,4.5,4.5,Estacionamiento gratis # Internet gratuito # P...,3.0
...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,Estacionamiento gratis # Internet de alta velo...,3.0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,Estacionamiento gratis # Internet de alta velo...,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,Internet de alta velocidad gratuito (WiFi) # P...,3.5
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,Internet de alta velocidad gratuito (WiFi) # W...,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085 # 4085 # 4085 # 4085 # 3689,4.5,5.0,Estacionamiento gratis # Internet de alta velo...,5.0

In [68]:
trip = trip.drop_duplicates()

In [69]:
trip.to_csv('./data/trip_clean.csv')

In [70]:
tripOHE = trip.drop("services",axis=1).join(trip.services.str.get_dummies(sep=" # "))
tripOHE

,city,comments,name,prices,quality_price,rating,stars,DVD,música para niños,Actividades infantiles (Ideal para niños / familias),...,Tienda de regalos,Transporte al aeropuerto,Utensilios de cocina,Vista a la ciudad,Vista a la montaña,Vista a la piscina,Vista a un lugar de interés,Vista al mar,Wifi,Wifi público
679,Bacalar,113,Villas Bakalar Hotel,2045 # 1840 # 1927,4.0,4.0,5.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562 # 656 # 656 # 656 # 627,4.5,4.5,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
696,Bacalar,128,Hotel Hacienda Bacalar,950 # 950 # 950,4.0,3.5,3.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
698,Bacalar,55,Azul 36 Hotel,1744 # 1744 # 1744 # 1492 # 1492,2.0,4.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250 # 2250,4.5,4.5,3.0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756 # 12756 # 12756 # 12756 # 12760 # 12756,4.5,4.5,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477 # 4477 # 4477 # 4499 # 4477 # 4478,4.5,4.5,3.5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199 # 2826 # 2812,5.0,4.5,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085 # 4085 # 4085 # 4085 # 3689,4.5,5.0,5.0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [71]:
tripOHE.prices = trip.prices.apply(lambda x: int(x.split("#")[0]) if str(x)!="nan" else np.nan)
tripOHE

,city,comments,name,prices,quality_price,rating,stars,DVD,música para niños,Actividades infantiles (Ideal para niños / familias),...,Tienda de regalos,Transporte al aeropuerto,Utensilios de cocina,Vista a la ciudad,Vista a la montaña,Vista a la piscina,Vista a un lugar de interés,Vista al mar,Wifi,Wifi público
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [72]:
tripOHE.to_csv('./data/tripadvisorSolPlaya_OHE.csv',index=False)

## Reducción de servicios en categorías:
+ **Heredados** Aquellos que provienen de recursos naturales
+ **Acceso y comunicación** Aquellos que permiten una comunicación al huésped, como el habla de idiomas extranjeros, wifi, teléfono, transporte, etc.
+ **Entretenimiento** Actividades extras dentro y fuera del hotel.
+ **Inclusión** Aquellos servicios que tienen en cuenta a personas algún tipo de discapacidad.
+ **Apto para infantes** Servicios que indican la inclusión de niños.
+ **Restaurante/Bar** Servicios en relación a la comida y bebidas.
+ **~Pet Friendly** Si las mascotas son permitidas o no dentro del hotel

In [73]:
trip_servicios = tripOHE[tripOHE.columns[:7]].copy()
trip_servicios

,city,comments,name,prices,quality_price,rating,stars
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0
...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0

In [74]:
list(tripOHE.columns[7:])

[' DVD',
 ' música para niños',
 'Actividades infantiles (Ideal para niños / familias)',
 'Aire acondicionado',
 'Almacenamiento de equipaje',
 'Alquiler de bicicletas',
 'Balcón privado',
 'Bar/Salón',
 'Batas de baño',
 'Bañera con hidromasaje',
 'Bañera de hidromasaje',
 'Bañera/Ducha',
 'Baño adicional',
 'Baños privados',
 'Bicicletas disponibles',
 'Botellas de agua',
 'Buceo',
 'Cadenas de televisión para niños',
 'Cafetería',
 'Café instantáneo gratis',
 'Caja fuerte',
 'Camas extralargas',
 'Cambio de divisas',
 'Campo de golf',
 'Canotaje',
 'Centro de negocios con acceso a Internet',
 'Check-in y check-out exprés',
 'Clases de yoga',
 'Cocina',
 'Comedor',
 'Conserje',
 'Cortinas blackout',
 'Desayuno disponible',
 'Desayuno gratis',
 'Ducha a ras de suelo',
 'Equipo para niños para jugar al aire libre',
 'Escritorio',
 'Esnórquel',
 'Estacionamiento',
 'Estacionamiento en la calle',
 'Estacionamiento gratis',
 'Estacionamiento gratuito privado cercano',
 'Estacionamiento privado pagado cercano',
 'Estacionamiento público gratuito cercano',
 'Estacionamiento vigilado',
 'Estante para la ropa',
 'Excursionismo',
 'Fotocopiadora/Fax en el centro de negocios',
 'Garaje de estacionamientos',
 'Gimnasio / Sala de entrenamiento',
 'Guardarropa/Ropero',
 'Guardería',
 'Habitaciones insonorizadas',
 'Habitaciones interconectadas disponibles',
 'Habitaciones para familias',
 'Habitaciones para fumadores disponibles',
 'Habitaciones para no fumadores',
 'Habitación libre de alérgenos',
 'Hotel para no fumadores',
 'Instalaciones para conferencias',
 'Instalaciones para hacer parrillas',
 'Internet',
 'Internet de alta velocidad gratuito (WiFi)',
 'Internet gratuito',
 'Juegos de mesa/Rompecabezas',
 'Kit de primeros auxilios',
 'Kitchenette',
 'Libros',
 'Limpieza en seco',
 'Los niños se alojan gratis',
 'Masaje',
 'Masaje de cuerpo completo',
 'Masaje en pareja',
 'Microondas',
 'Minibar',
 'Muebles de exterior',
 'Máquina de café/té',
 'Navegación',
 'Patio de juegos para niños',
 'Pesca',
 'Piscina',
 'Piscina al aire libre',
 'Piscina en la terraza',
 'Piscina infinita',
 'Piscina para niños',
 'Piso de azulejos/mármol',
 'Plancha',
 'Playa',
 'Playa privada',
 'Productos de tocador de cortesía',
 'Recepción disponible las 24\xa0horas',
 'Red para mosquitos',
 'Refrigerador',
 'Restaurante',
 'Sala de estar',
 'Sala de juegos',
 'Salas de reuniones',
 'Salón de banquetes',
 'Sauna',
 'Se admiten mascotas ( Se aceptan perros / mascotas )',
 'Secador de pelo',
 'Seguridad las 24\xa0horas',
 'Servicio a la habitación',
 'Servicio de despertador/Reloj despertador',
 'Servicio de lavandería',
 'Servicio de limpieza',
 'Servicio de taxi',
 'Sillitas altas disponibles',
 'Solo para adultos',
 'Solárium',
 'Sombrillas',
 'Spa',
 'Suite nupcial',
 'Suites',
 'TV pantalla plana',
 'TV por cable/satélite',
 'Terraza en la azotea',
 'Tienda de regalos',
 'Transporte al aeropuerto',
 'Utensilios de cocina',
 'Vista a la ciudad',
 'Vista a la montaña',
 'Vista a la piscina',
 'Vista a un lugar de interés',
 'Vista al mar',
 'Wifi',
 'Wifi público']

### Heredados

In [75]:
heredados_t = [
'Pesca','Playa','Playa privada', 
'Vista a la montaña', 'Vista al mar',
]

In [76]:
trip_servicios['heredados'] =  tripOHE[heredados_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1
...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0

In [77]:
trip_servicios['total_heredados'] = tripOHE[heredados_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1
...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0

### Acceso y comunicación

In [78]:
acceso_t = [
'Alquiler de bicicletas',
'Bicicletas disponibles', 'Internet',
'Internet de alta velocidad gratuito (WiFi)',
'Internet gratuito', 'Servicio de taxi',
 'Transporte al aeropuerto',
'Wifi',
'Wifi público'
]

In [79]:
trip_servicios['acceso/comunicacion'] = tripOHE[acceso_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1
...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1

In [80]:
trip_servicios['total_acceso/comunicacion'] = tripOHE[acceso_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2

### Entretenimiento

In [81]:
entretenimiento_t = [
' DVD', 'Campo de golf',
 'Canotaje',
'Clases de yoga',
'Excursionismo', 'Gimnasio / Sala de entrenamiento',
'Juegos de mesa/Rompecabezas',
'Libros', 'Piscina',
'Piscina al aire libre',
'Piscina en la terraza', 'Piscina infinita',
'Sala de juegos',
'TV pantalla plana',
'TV por cable/satélite'
]

In [82]:
trip_servicios['entretenimiento/deporte'] = tripOHE[entretenimiento_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1

In [83]:
trip_servicios['total_entretenimiento/deporte'] = tripOHE[entretenimiento_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0,0
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1,5
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1,1
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1,3
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3

## Inclusión
Dentro de los servicios que toman en cuenta, no especifican ninguno relacionado a la inclusión de personas con alguna discapacidad.

### Niños

In [84]:
ninios_t = [
' música para niños',
'Actividades infantiles (Ideal para niños / familias)',
'Cadenas de televisión para niños',
'Equipo para niños para jugar al aire libre',
'Guardería', 'Habitaciones para familias',
'Los niños se alojan gratis', 'Patio de juegos para niños',
'Piscina para niños'
]

In [85]:
trip_servicios['ninios'] = tripOHE[ninios_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0,0,1
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1,5,1
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1,1,1
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1,3,1
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3,0

In [86]:
trip_servicios['total_ninios'] = tripOHE[ninios_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2,0,0
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0,0,1,1
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1,5,1,3
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1,1,1,1
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1,1,2
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1,0,0
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2,1,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1,3,1,1
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3,0,0

### Comida

In [87]:
comida_t = [
'Bar/Salón',
'Cafetería', 'Café instantáneo gratis',
'Cocina', 'Comedor', 'Desayuno disponible',
'Desayuno gratis', 'Kitchenette',
'Microondas', 'Minibar', 'Máquina de café/té',
'Refrigerador',
'Restaurante', 
]

In [88]:
trip_servicios['comida/bebida'] = tripOHE[comida_t].any(axis=1).astype('int16')
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2,0,0,1
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0,0,1,1,1
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1,5,1,3,0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1,1,1,1,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1,1,2,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1,0,0,1
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2,1,1,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1,3,1,1,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3,0,0,1

In [89]:
trip_servicios['total_comida/bebida'] = tripOHE[comida_t].sum(axis=1)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida,total_comida/bebida
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2,0,0,1,3
694,Bacalar,197,Hostal & Suites Pata de Perro,562,4.5,4.5,0,0,0,1,3,0,0,1,1,1,4
696,Bacalar,128,Hotel Hacienda Bacalar,950,4.0,3.5,3.0,0,0,1,2,1,5,1,3,0,0
698,Bacalar,55,Azul 36 Hotel,1744,2.0,4.0,0,0,0,1,2,1,1,1,1,0,0
703,Mazunte,107,Casa Mermejita Villa vacacional,2250,4.5,4.5,3.0,1,1,1,1,1,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1,1,2,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1,0,0,1,3
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2,1,1,1,1
1419,Todos Santos,69,Perro Surfero Boutique Hotel B & B,2199,5.0,4.5,0,0,0,1,2,1,3,1,1,0,0
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3,0,0,1,2

In [90]:
trip_servicios.sort_values(by="city",inplace=True)
trip_servicios

,city,comments,name,prices,quality_price,rating,stars,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida,total_comida/bebida
679,Bacalar,113,Villas Bakalar Hotel,2045,4.0,4.0,5.0,0,0,1,2,1,2,0,0,1,3
1146,Bacalar,25,Casa Zazil Villa vacacional,1355,4.0,5.0,0,0,0,1,3,1,1,1,1,1,3
1145,Bacalar,15,Casa Delia Hotel,1050,4.5,4.5,0,0,0,0,0,0,0,1,1,0,0
1142,Bacalar,26,Hotel Casa Lima,893,4.5,4.0,0,0,0,1,2,0,0,1,2,1,1
1140,Bacalar,17,Hotel ADE,1019,0.0,3.5,0,0,0,1,3,0,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,Todos Santos,123,Serendipity B & B,3387,5.0,5.0,5.0,1,2,1,1,1,1,1,2,1,3
1416,Todos Santos,104,La Bohemia Baja Hotel Pequeno,2904,5.0,4.5,3.0,0,0,1,2,1,1,1,2,1,1
1417,Todos Santos,95,Paradero Todos Santos Hotel,12756,4.5,4.5,0,0,0,1,2,1,1,0,0,1,3
1418,Todos Santos,429,Guaycura Boutique Hotel Beach Club & Spa,4477,4.5,4.5,3.5,1,1,1,2,1,2,1,1,1,1
1420,Todos Santos,103,Hacienda Todos Los Santos Hotel,4085,4.5,5.0,5.0,0,0,1,2,1,3,0,0,1,2

In [91]:
trip_servicios.describe()

,comments,prices,quality_price,rating,heredados,total_heredados,acceso/comunicacion,total_acceso/comunicacion,entretenimiento/deporte,total_entretenimiento/deporte,ninios,total_ninios,comida/bebida,total_comida/bebida
count,83.000000,83.000000,83.000000,76.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000,83.000000
mean,120.060241,2078.048193,2.777108,4.210526,0.253012,0.409639,0.674699,1.265060,0.506024,0.951807,0.578313,0.843373,0.578313,1.132530
std,208.313340,1791.305668,2.117369,0.639078,0.437381,0.812046,0.471335,1.025104,0.503003,1.198613,0.496831,0.876272,0.496831,1.276152
min,0.000000,562.000000,0.000000,1.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.500000,1097.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,33.000000,1584.000000,4.000000,4.500000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,125.500000,2354.000000,4.500000,4.500000,0.500000,0.500000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000
max,1019.000000,12756.000000,5.000000,5.000000,1.000000,3.000000,1.000000,4.000000,1.000000,5.000000,1.000000,3.000000,1.000000,5.000000

In [92]:
trip_servicios.to_csv('./data/trip_servicios_sumas_clasificados.csv',index=False)